#include "classifier.h"

/* Autogenerated code from the script config2c.pl */

static const char *protor_residue_name[] = {"A", "ACE", "ALA", "ARG", "ASN", "ASP", "ASX", "C", "CYS", "DA", "DC", "DG", "DI", "DT", "DU", "G", "GLN", "GLU", "GLX", "GLY", "HIS", "HOH", "I", "ILE", "LEU", "LYS", "MET", "NH2", "PHE", "PRO", "PYL", "SEC", "SER", "T", "THR", "TRP", "TYR", "U", "VAL", };
static const char *protor_A_atom_name[] = {"N6", "C5", "O5'", "C2", "P", "C4", "OP2", "C3'", "N1", "C4'", "C2'", "C8", "C5'", "N7", "O3'", "C6", "N9", "OP1", "C1'", "N3", "OP3", "O2'", "O4'", };
static double protor_A_atom_radius[] = {1.64, 1.61, 1.46, 1.76, 1.8, 1.61, 1.46, 1.88, 1.64, 1.88, 1.88, 1.76, 1.88, 1.64, 1.46, 1.61, 1.64, 1.42, 1.88, 1.64, 1.46, 1.46, 1.46, };
static int protor_A_atom_class[] = {FREESASA_ATOM_POLAR, FREESASA_ATOM_APOLAR, FREESASA_ATOM_POLAR, FREESASA_ATOM_APOLAR, FREESASA_ATOM_POLAR, FREESASA_ATOM_APOLAR, FREESASA_ATOM_POLAR, FREESASA_ATOM_APOLAR, FREESASA_ATOM_POLAR, FREESASA_ATOM_APOLAR, FREESASA_ATOM_APOLAR, FREESASA_ATOM_APOLAR, FREESASA_ATOM_APOLAR, FREESASA_ATOM_POLAR, FREESASA_ATOM_POLAR, FREESASA_ATOM_APOLAR, FREESASA_ATOM_POLAR, FREESASA_ATOM_POLAR, FREESASA_ATOM_APOLAR, FREESASA_ATOM_POLAR, FREESASA_ATOM_POLAR, FREESASA_ATOM_POLAR, FREESASA_ATOM_POLAR, };
static struct classifier_residue protor_A_cfg = {
    .name = "A", .n_atoms = 23,
    .atom_name = (char**) protor_A_atom_name,
    .atom_radius = (double*) protor_A_atom_radius,
    .atom_class = (freesasa_atom_class*) protor_A_atom_class,
    .max_area = {NULL, 0, 0, 0, 0, 0},
};

static const char *protor_ACE_atom_name[] = {"CH3", "O", "C", };
static double protor_ACE_atom_radius[] = {1.88, 1.42, 1.76, };
static int protor_ACE_atom_class[] = {FREESASA_ATOM_APOLAR, FREESASA_ATOM_POLAR, FREESASA_ATOM_APOLAR, };
static struct classifier_residue protor_ACE_cfg = {
    .name = "ACE", .n_atoms = 3,
    .atom_name = (char**) protor_ACE_atom_name,
    .atom_radius = (double*) protor_ACE_atom_radius,
    .atom_class = (freesasa_atom_class*) protor_ACE_atom_class,
    .max_area = {NULL, 0, 0, 0, 0, 0},
};

static const char *protor_ALA_atom_name[] = {"OXT", "CA", "N", "O", "C", "CB", };
static double protor_ALA_atom_radius[] = {1.46, 1.88, 1.64, 1.42, 1.61, 1.88, };
static int protor_ALA_atom_class[] = {FREESASA_ATOM_POLAR, FREESASA_ATOM_APOLAR, FREESASA_ATOM_POLAR, FREESASA_ATOM_POLAR, FREESASA_ATOM_APOLAR, FREESASA_ATOM_APOLAR, };
static struct classifier_residue protor_ALA_cfg = {
    .name = "ALA", .n_atoms = 6,
    .atom_name = (char**) protor_ALA_atom_name,
    .atom_radius = (double*) protor_ALA_atom_radius,
    .atom_class = (freesasa_atom_class*) protor_ALA_atom_class,
    .max_area = {.name = "ALA", .total = 108.76, .main_chain = 43.96, .side_chain = 64.80, .polar = 37.75, .apolar = 71.01},
};

static const char *protor_ARG_atom_name[] = {"CG", "CA", "NE", "NH2", "NH1", "N", "OXT", "CZ", "CD", "C", "CB", "O", };
static double protor_ARG_atom_radius[] = {1.88, 1.88, 1.64, 1.64, 1.64, 1.64, 1.46, 1.61, 1.88, 1.61, 1.88, 1.42, };
static int protor_ARG_atom_class[] = {FREESASA_ATOM_APOLAR, FREESASA_ATOM_APOLAR, FREESASA_ATOM_POLAR, FREESASA_ATOM_POLAR, FREESASA_ATOM_POLAR, FREESASA_ATOM_POLAR, FREESASA_ATOM_POLAR, FREESASA_ATOM_APOLAR, FREESASA_ATOM_APOLAR, FREESASA_ATOM_APOLAR, FREESASA_ATOM_APOLAR, FREESASA_ATOM_POLAR, };
static struct classifier_residue protor_ARG_cfg = {
    .name = "ARG", .n_atoms = 12,
    .atom_name = (char**) protor_ARG_atom_name,
    .atom_radius = (double*) protor_ARG_atom_radius,
    .atom_class = (freesasa_atom_class*) protor_ARG_atom_class,
    .max_area = {.name = "ARG", .total = 238.17, .main_chain = 42.00, .side_chain = 196.17, .polar = 165.00, .apolar = 73.17},
};

static const char *protor_ASN_atom_name[] = {"OD1", "CG", "CA", "C", "CB", "O", "N", "OXT", "ND2", };
static double protor_ASN_atom_radius[] = {1.42, 1.61, 1.88, 1.61, 1.88, 1.42, 1.64, 1.46, 1.64, };
static int protor_ASN_atom_class[] = {FREESASA_ATOM_POLAR, FREESASA_ATOM_APOLAR, FREESASA_ATOM_APOLAR, FREESASA_ATOM_APOLAR, FREESASA_ATOM_APOLAR, FREESASA_ATOM_POLAR, FREESASA_ATOM_POLAR, FREESASA_ATOM_POLAR, FREESASA_ATOM_POLAR, };
static struct classifier_residue protor_ASN_cfg = {
    .name = "ASN", .n_atoms = 9,
    .atom_name = (char**) protor_ASN_atom_name,
    .atom_radius = (double*) protor_ASN_atom_radius,
    .atom_class = (freesasa_atom_class*) protor_ASN_atom_class,
    .max_area = {.name = "ASN", .total = 145.01, .main_chain = 41.53, .side_chain = 103.48, .polar = 103.46, .apolar = 41.55},
};

static const char *protor_ASP_atom_name[] = {"CG", "CA", "OD1", "OD2", "N", "OXT", "C", "CB", "O", };
static double protor_ASP_atom_radius[] = {1.61, 1.88, 1.42, 1.46, 1.64, 1.46, 1.61, 1.88, 1.42, };
static int protor_ASP_atom_class[] = {FREESASA_ATOM_APOLAR, FREESASA_ATOM_APOLAR, FREESASA_ATOM_POLAR, FREESASA_ATOM_POLAR, FREESASA_ATOM_POLAR, FREESASA_ATOM_POLAR, FREESASA_ATOM_APOLAR, FREESASA_ATOM_APOLAR, FREESASA_ATOM_POLAR, };
static struct classifier_residue protor_ASP_cfg = {
    .name = "ASP", .n_atoms = 9,
    .atom_name = (char**) protor_ASP_atom_name,
    .atom_radius = (double*) protor_ASP_atom_radius,
    .atom_class = (freesasa_atom_class*) protor_ASP_atom_class,
    .max_area = {.name = "ASP", .total = 142.76, .main_chain = 42.29, .side_chain = 100.47, .polar = 100.27, .apolar = 42.49},
};

static const char *protor_ASX_atom_name[] = {"XD2", "CA", "CG", "XD1", "OXT", "N", "O", "C", "CB", };
static double protor_ASX_atom_radius[] = {1.5, 1.88, 1.61, 1.5, 1.46, 1.64, 1.42, 1.61, 1.88, };
static int protor_ASX_atom_class[] = {FREESASA_ATOM_POLAR, FREESASA_ATOM_APOLAR, FREESASA_ATOM_APOLAR, FREESASA_ATOM_POLAR, FREESASA_ATOM_POLAR, FREESASA_ATOM_POLAR, FREESASA_ATOM_POLAR, FREESASA_ATOM_APOLAR, FREESASA_ATOM_APOLAR, };
static struct classifier_residue protor_ASX_cfg = {
    .name = "ASX", .n_atoms = 9,
    .atom_name = (char**) protor_ASX_atom_name,
    .atom_radius = (double*) protor_ASX_atom_radius,
    .atom_class = (freesasa_atom_class*) protor_ASX_atom_class,
    .max_area = {NULL, 0, 0, 0, 0, 0},
};

static const char *protor_C_atom_name[] = {"C5", "P", "O2", "C2", "O5'", "C3'", "OP2", "C4", "C2'", "N4", "C4'", "N1", "O3'", "C5'", "C1'", "OP1", "C6", "N3", "O4'", "OP3", "O2'", };
static double protor_C_atom_radius[] = {1.76, 1.8, 1.42, 1.61, 1.46, 1.88, 1.46, 1.61, 1.88, 1.64, 1.88, 1.64, 1.46, 1.88, 1.88, 1.42, 1.76, 1.64, 1.46, 1.46, 1.46, };
static int protor_C_atom_class[] = {FREESASA_ATOM_APOLAR, FREESASA_ATOM_POLAR, FREESASA_ATOM_POLAR, FREESASA_ATOM_APOLAR, FREESASA_ATOM_POLAR, FREESASA_ATOM_APOLAR, FREESASA_ATOM_POLAR, FREESASA_ATOM_APOLAR, FREESASA_ATOM_APOLAR, FREESASA_ATOM_POLAR, FREESASA_ATOM_APOLAR, FREESASA_ATOM_POLAR, FREESASA_ATOM_POLAR, FREESASA_ATOM_APOLAR, FREESASA_ATOM_APOLAR, FREESASA_ATOM_POLAR, FREESASA_ATOM_APOLAR, FREESASA_ATOM_POLAR, FREESASA_ATOM_POLAR, FREESASA_ATOM_POLAR, FREESASA_ATOM_POLAR, };
static struct classifier_residue protor_C_cfg = {
    .name = "C", .n_atoms = 21,
    .atom_name = (char**) protor_C_atom_name,
    .atom_radius = (double*) protor_C_atom_radius,
    .atom_class = (freesasa_atom_class*) protor_C_atom_class,
    .max_area = {NULL, 0, 0, 0, 0, 0},
};

static const char *protor_CYS_atom_name[] = {"O", "SG", "C", "CB", "OXT", "N", "CA", };
static double protor_CYS_atom_radius[] = {1.42, 1.77, 1.61, 1.88, 1.46, 1.64, 1.88, };
static int protor_CYS_atom_class[] = {FREESASA_ATOM_POLAR, FREESASA_ATOM_POLAR, FREESASA_ATOM_APOLAR, FREESASA_ATOM_APOLAR, FREESASA_ATOM_POLAR, FREESASA_ATOM_POLAR, FREESASA_ATOM_APOLAR, };
static struct classifier_residue protor_CYS_cfg = {
    .name = "CYS", .n_atoms = 7,
    .atom_name = (char**) protor_CYS_atom_name,
    .atom_radius = (double*) protor_CYS_atom_radius,
    .atom_class = (freesasa_atom_class*) protor_CYS_atom_class,
    .max_area = {.name = "CYS", .total = 132.20, .main_chain = 42.55, .side_chain = 89.66, .polar = 92.74, .apolar = 39.47},
};

static const char *protor_DA_atom_name[] = {"C1'", "N9", "C6", "OP1", "O3'", "N7", "C5'", "C8", "O4'", "OP3", "N3", "P", "C2", "O5'", "N6", "C5", "C4'", "C2'", "N1", "C3'", "OP2", "C4", };
static double protor_DA_atom_radius[] = {1.88, 1.64, 1.61, 1.42, 1.46, 1.64, 1.88, 1.76, 1.46, 1.46, 1.64, 1.8, 1.76, 1.46, 1.64, 1.61, 1.88, 1.88, 1.64, 1.88, 1.46, 1.61, };
static int protor_DA_atom_class[] = {FREESASA_ATOM_APOLAR, FREESASA_ATOM_POLAR, FREESASA_ATOM_APOLAR, FREESASA_ATOM_POLAR, FREESASA_ATOM_POLAR, FREESASA_ATOM_POLAR, FREESASA_ATOM_APOLAR, FREESASA_ATOM_APOLAR, FREESASA_ATOM_POLAR, FREESASA_ATOM_POLAR, FREESASA_ATOM_POLAR, FREESASA_ATOM_POLAR, FREESASA_ATOM_APOLAR, FREESASA_ATOM_POLAR, FREESASA_ATOM_POLAR, FREESASA_ATOM_APOLAR, FREESASA_ATOM_APOLAR, FREESASA_ATOM_APOLAR, FREESASA_ATOM_POLAR, FREESASA_ATOM_APOLAR, FREESASA_ATOM_POLAR, FREESASA_ATOM_APOLAR, };
static struct classifier_residue protor_DA_cfg = {
    .name = "DA", .n_atoms = 22,
    .atom_name = (char**) protor_DA_atom_name,
    .atom_radius = (double*) protor_DA_atom_radius,
    .atom_class = (freesasa_atom_class*) protor_DA_atom_class,
    .max_area = {NULL, 0, 0, 0, 0, 0},
};

static const char *protor_DC_atom_name[] = {"OP3", "O4'", "N3", "C6", "OP1", "C1'", "C5'", "O3'", "N1", "N4", "C4'", "C2'", "C4", "OP2", "C3'", "O5'", "C2", "O2", "P", "C5", };
static double protor_DC_atom_radius[] = {1.46, 1.46, 1.64, 1.76, 1.42, 1.88, 1.88, 1.46, 1.64, 1.64, 1.88, 1.88, 1.61, 1.46, 1.88, 1.46, 1.61, 1.42, 1.8, 1.76, };
static int protor_DC_atom_class[] = {FREESASA_ATOM_POLAR, FREESASA_ATOM_POLAR, FREESASA_ATOM_POLAR, FREESASA_ATOM_APOLAR, FREESASA_ATOM_POLAR, FREESASA_ATOM_APOLAR, FREESASA_ATOM_APOLAR, FREESASA_ATOM_POLAR, FREESASA_ATOM_POLAR, FREESASA_ATOM_POLAR, FREESASA_ATOM_APOLAR, FREESASA_ATOM_APOLAR, FREESASA_ATOM_APOLAR, FREESASA_ATOM_POLAR, FREESASA_ATOM_APOLAR, FREESASA_ATOM_POLAR, FREESASA_ATOM_APOLAR, FREESASA_ATOM_POLAR, FREESASA_ATOM_POLAR, FREESASA_ATOM_APOLAR, };
static struct classifier_residue protor_DC_cfg = {
    .name = "DC", .n_atoms = 20,
    .atom_name = (char**) protor_DC_atom_name,
    .atom_radius = (double*) protor_DC_atom_radius,
    .atom_class = (freesasa_atom_class*) protor_DC_atom_class,
    .max_area = {NULL, 0, 0, 0, 0, 0},
};

static const char *protor_DG_atom_name[] = {"C1'", "OP1", "O6", "C6", "N9", "C5'", "C8", "O3'", "N7", "N2", "OP3", "O4'", "N3", "O5'", "P", "C2", "C5", "N1", "C2'", "C4'", "C4", "C3'", "OP2", };
static double protor_DG_atom_radius[] = {1.88, 1.42, 1.42, 1.61, 1.64, 1.88, 1.76, 1.46, 1.64, 1.64, 1.46, 1.46, 1.64, 1.46, 1.8, 1.61, 1.61, 1.64, 1.88, 1.88, 1.61, 1.88, 1.46, };
static int protor_DG_atom_class[] = {FREESASA_ATOM_APOLAR, FREESASA_ATOM_POLAR, FREESASA_ATOM_POLAR, FREESASA_ATOM_APOLAR, FREESASA_ATOM_POLAR, FREESASA_ATOM_APOLAR, FREESASA_ATOM_APOLAR, FREESASA_ATOM_POLAR, FREESASA_ATOM_POLAR, FREESASA_ATOM_POLAR, FREESASA_ATOM_POLAR, FREESASA_ATOM_POLAR, FREESASA_ATOM_POLAR, FREESASA_ATOM_POLAR, FREESASA_ATOM_POLAR, FREESASA_ATOM_APOLAR, FREESASA_ATOM_APOLAR, FREESASA_ATOM_POLAR, FREESASA_ATOM_APOLAR, FREESASA_ATOM_APOLAR, FREESASA_ATOM_APOLAR, FREESASA_ATOM_APOLAR, FREESASA_ATOM_POLAR, };
static struct classifier_residue protor_DG_cfg = {
    .name = "DG", .n_atoms = 23,
    .atom_name = (char**) protor_DG_atom_name,
    .atom_radius = (double*) protor_DG_atom_radius,
    .atom_class = (freesasa_atom_class*) protor_DG_atom_class,
    .max_area = {NULL, 0, 0, 0, 0, 0},
};

static const char *protor_DI_atom_name[] = {"N7", "O3'", "C5'", "C8", "C1'", "C6", "O6", "N9", "OP1", "N3", "O4'", "OP3", "C5", "P", "C2", "O5'", "C3'", "OP2", "C4", "C4'", "C2'", "N1", };
static double protor_DI_atom_radius[] = {1.64, 1.46, 1.88, 1.76, 1.88, 1.61, 1.42, 1.64, 1.42, 1.64, 1.46, 1.46, 1.61, 1.8, 1.76, 1.46, 1.88, 1.46, 1.61, 1.88, 1.88, 1.64, };
static int protor_DI_atom_class[] = {FREESASA_ATOM_POLAR, FREESASA_ATOM_POLAR, FREESASA_ATOM_APOLAR, FREESASA_ATOM_APOLAR, FREESASA_ATOM_APOLAR, FREESASA_ATOM_APOLAR, FREESASA_ATOM_POLAR, FREESASA_ATOM_POLAR, FREESASA_ATOM_POLAR, FREESASA_ATOM_POLAR, FREESASA_ATOM_POLAR, FREESASA_ATOM_POLAR, FREESASA_ATOM_APOLAR, FREESASA_ATOM_POLAR, FREESASA_ATOM_APOLAR, FREESASA_ATOM_POLAR, FREESASA_ATOM_APOLAR, FREESASA_ATOM_POLAR, FREESASA_ATOM_APOLAR, FREESASA_ATOM_APOLAR, FREESASA_ATOM_APOLAR, FREESASA_ATOM_POLAR, };
static struct classifier_residue protor_DI_cfg = {
    .name = "DI", .n_atoms = 22,
    .atom_name = (char**) protor_DI_atom_name,
    .atom_radius = (double*) protor_DI_atom_radius,
    .atom_class = (freesasa_atom_class*) protor_DI_atom_class,
    .max_area = {NULL, 0, 0, 0, 0, 0},
};

static const char *protor_DT_atom_name[] = {"C4'", "C2'", "N1", "C3'", "OP2", "C4", "P", "O2", "C2", "O5'", "C5", "O4'", "C7", "OP3", "N3", "O4", "C1'", "C6", "OP1", "O3'", "C5'", };
static double protor_DT_atom_radius[] = {1.88, 1.88, 1.64, 1.88, 1.46, 1.61, 1.8, 1.42, 1.61, 1.46, 1.61, 1.46, 1.88, 1.46, 1.64, 1.42, 1.88, 1.76, 1.42, 1.46, 1.88, };
static int protor_DT_atom_class[] = {FREESASA_ATOM_APOLAR, FREESASA_ATOM_APOLAR, FREESASA_ATOM_POLAR, FREESASA_ATOM_APOLAR, FREESASA_ATOM_POLAR, FREESASA_ATOM_APOLAR, FREESASA_ATOM_POLAR, FREESASA_ATOM_POLAR, FREESASA_ATOM_APOLAR, FREESASA_ATOM_POLAR, FREESASA_ATOM_APOLAR, FREESASA_ATOM_POLAR, FREESASA_ATOM_APOLAR, FREESASA_ATOM_POLAR, FREESASA_ATOM_POLAR, FREESASA_ATOM_POLAR, FREESASA_ATOM_APOLAR, FREESASA_ATOM_APOLAR, FREESASA_ATOM_POLAR, FREESASA_ATOM_POLAR, FREESASA_ATOM_APOLAR, };
static struct classifier_residue protor_DT_cfg = {
    .name = "DT", .n_atoms = 21,
    .atom_name = (char**) protor_DT_atom_name,
    .atom_radius = (double*) protor_DT_atom_radius,
    .atom_class = (freesasa_atom_class*) protor_DT_atom_class,
    .max_area = {NULL, 0, 0, 0, 0, 0},
};

static const char *protor_DU_atom_name[] = {"O5'", "P", "O2", "C2", "C5", "N1", "C2'", "C4'", "C4", "C3'", "OP2", "C1'", "O4", "C6", "OP1", "C5'", "O3'", "OP3", "O4'", "N3", };
static double protor_DU_atom_radius[] = {1.46, 1.8, 1.42, 1.61, 1.76, 1.64, 1.88, 1.88, 1.61, 1.88, 1.46, 1.88, 1.42, 1.76, 1.42, 1.88, 1.46, 1.46, 1.46, 1.64, };
static int protor_DU_atom_class[] = {FREESASA_ATOM_POLAR, FREESASA_ATOM_POLAR, FREESASA_ATOM_POLAR, FREESASA_ATOM_APOLAR, FREESASA_ATOM_APOLAR, FREESASA_ATOM_POLAR, FREESASA_ATOM_APOLAR, FREESASA_ATOM_APOLAR, FREESASA_ATOM_APOLAR, FREESASA_ATOM_APOLAR, FREESASA_ATOM_POLAR, FREESASA_ATOM_APOLAR, FREESASA_ATOM_POLAR, FREESASA_ATOM_APOLAR, FREESASA_ATOM_POLAR, FREESASA_ATOM_APOLAR, FREESASA_ATOM_POLAR, FREESASA_ATOM_POLAR, FREESASA_ATOM_POLAR, FREESASA_ATOM_POLAR, };
static struct classifier_residue protor_DU_cfg = {
    .name = "DU", .n_atoms = 20,
    .atom_name = (char**) protor_DU_atom_name,
    .atom_radius = (double*) protor_DU_atom_radius,
    .atom_class = (freesasa_atom_class*) protor_DU_atom_class,
    .max_area = {NULL, 0, 0, 0, 0, 0},
};

static const char *protor_G_atom_name[] = {"O4'", "N2", "O2'", "OP3", "N3", "C1'", "C6", "O6", "N9", "OP1", "N7", "O3'", "C5'", "C8", "C2'", "C4'", "N1", "C3'", "OP2", "C4", "P", "C2", "O5'", "C5", };
static double protor_G_atom_radius[] = {1.46, 1.64, 1.46, 1.46, 1.64, 1.88, 1.61, 1.42, 1.64, 1.42, 1.64, 1.46, 1.88, 1.76, 1.88, 1.88, 1.64, 1.88, 1.46, 1.61, 1.8, 1.61, 1.46, 1.61, };
static int protor_G_atom_class[] = {FREESASA_ATOM_POLAR, FREESASA_ATOM_POLAR, FREESASA_ATOM_POLAR, FREESASA_ATOM_POLAR, FREESASA_ATOM_POLAR, FREESASA_ATOM_APOLAR, FREESASA_ATOM_APOLAR, FREESASA_ATOM_POLAR, FREESASA_ATOM_POLAR, FREESASA_ATOM_POLAR, FREESASA_ATOM_POLAR, FREESASA_ATOM_POLAR, FREESASA_ATOM_APOLAR, FREESASA_ATOM_APOLAR, FREESASA_ATOM_APOLAR, FREESASA_ATOM_APOLAR, FREESASA_ATOM_POLAR, FREESASA_ATOM_APOLAR, FREESASA_ATOM_POLAR, FREESASA_ATOM_APOLAR, FREESASA_ATOM_POLAR, FREESASA_ATOM_APOLAR, FREESASA_ATOM_POLAR, FREESASA_ATOM_APOLAR, };
static struct classifier_residue protor_G_cfg = {
    .name = "G", .n_atoms = 24,
    .atom_name = (char**) protor_G_atom_name,
    .atom_radius = (double*) protor_G_atom_radius,
    .atom_class = (freesasa_atom_class*) protor_G_atom_class,
    .max_area = {NULL, 0, 0, 0, 0, 0},
};

static const char *protor_GLN_atom_name[] = {"N", "CD", "OXT", "C", "CB", "OE1", "O", "CA", "CG", "NE2", };
static double protor_GLN_atom_radius[] = {1.64, 1.61, 1.46, 1.61, 1.88, 1.42, 1.42, 1.88, 1.88, 1.64, };
static int protor_GLN_atom_class[] = {FREESASA_ATOM_POLAR, FREESASA_ATOM_APOLAR, FREESASA_ATOM_POLAR, FREESASA_ATOM_APOLAR, FREESASA_ATOM_APOLAR, FREESASA_ATOM_POLAR, FREESASA_ATOM_POLAR, FREESASA_ATOM_APOLAR, FREESASA_ATOM_APOLAR, FREESASA_ATOM_POLAR, };
static struct classifier_residue protor_GLN_cfg = {
    .name = "GLN", .n_atoms = 10,
    .atom_name = (char**) protor_GLN_atom_name,
    .atom_radius = (double*) protor_GLN_atom_radius,
    .atom_class = (freesasa_atom_class*) protor_GLN_atom_class,
    .max_area = {.name = "GLN", .total = 178.83, .main_chain = 42.00, .side_chain = 136.83, .polar = 131.85, .apolar = 46.98},
};

static const char *protor_GLU_atom_name[] = {"OE2", "CG", "CA", "OE1", "O", "C", "CB", "CD", "OXT", "N", };
static double protor_GLU_atom_radius[] = {1.46, 1.88, 1.88, 1.42, 1.42, 1.61, 1.88, 1.61, 1.46, 1.64, };
static int protor_GLU_atom_class[] = {FREESASA_ATOM_POLAR, FREESASA_ATOM_APOLAR, FREESASA_ATOM_APOLAR, FREESASA_ATOM_POLAR, FREESASA_ATOM_POLAR, FREESASA_ATOM_APOLAR, FREESASA_ATOM_APOLAR, FREESASA_ATOM_APOLAR, FREESASA_ATOM_POLAR, FREESASA_ATOM_POLAR, };
static struct classifier_residue protor_GLU_cfg = {
    .name = "GLU", .n_atoms = 10,
    .atom_name = (char**) protor_GLU_atom_name,
    .atom_radius = (double*) protor_GLU_atom_radius,
    .atom_class = (freesasa_atom_class*) protor_GLU_atom_class,
    .max_area = {.name = "GLU", .total = 174.18, .main_chain = 42.00, .side_chain = 132.18, .polar = 122.48, .apolar = 51.70},
};

static const char *protor_GLX_atom_name[] = {"CG", "CA", "N", "OXT", "CD", "XE1", "C", "CB", "O", "XE2", };
static double protor_GLX_atom_radius[] = {1.88, 1.88, 1.64, 1.46, 1.61, 1.5, 1.61, 1.88, 1.42, 1.5, };
static int protor_GLX_atom_class[] = {FREESASA_ATOM_APOLAR, FREESASA_ATOM_APOLAR, FREESASA_ATOM_POLAR, FREESASA_ATOM_POLAR, FREESASA_ATOM_APOLAR, FREESASA_ATOM_POLAR, FREESASA_ATOM_APOLAR, FREESASA_ATOM_APOLAR, FREESASA_ATOM_POLAR, FREESASA_ATOM_POLAR, };
static struct classifier_residue protor_GLX_cfg = {
    .name = "GLX", .n_atoms = 10,
    .atom_name = (char**) protor_GLX_atom_name,
    .atom_radius = (double*) protor_GLX_atom_radius,
    .atom_class = (freesasa_atom_class*) protor_GLX_atom_class,
    .max_area = {NULL, 0, 0, 0, 0, 0},
};

static const char *protor_GLY_atom_name[] = {"CA", "N", "OXT", "C", "O", };
static double protor_GLY_atom_radius[] = {1.88, 1.64, 1.46, 1.61, 1.42, };
static int protor_GLY_atom_class[] = {FREESASA_ATOM_APOLAR, FREESASA_ATOM_POLAR, FREESASA_ATOM_POLAR, FREESASA_ATOM_APOLAR, FREESASA_ATOM_POLAR, };
static struct classifier_residue protor_GLY_cfg = {
    .name = "GLY", .n_atoms = 5,
    .atom_name = (char**) protor_GLY_atom_name,
    .atom_radius = (double*) protor_GLY_atom_radius,
    .atom_class = (freesasa_atom_class*) protor_GLY_atom_class,
    .max_area = {.name = "GLY", .total = 81.09, .main_chain = 81.09, .side_chain = 0.00, .polar = 44.65, .apolar = 36.44},
};

static const char *protor_HIS_atom_name[] = {"N", "ND1", "OXT", "CE1", "C", "CB", "O", "CA", "CG", "CD2", "NE2", };
static double protor_HIS_atom_radius[] = {1.64, 1.64, 1.46, 1.76, 1.61, 1.88, 1.42, 1.88, 1.61, 1.76, 1.64, };
static int protor_HIS_atom_class[] = {FREESASA_ATOM_POLAR, FREESASA_ATOM_POLAR, FREESASA_ATOM_POLAR, FREESASA_ATOM_APOLAR, FREESASA_ATOM_APOLAR, FREESASA_ATOM_APOLAR, FREESASA_ATOM_POLAR, FREESASA_ATOM_APOLAR, FREESASA_ATOM_APOLAR, FREESASA_ATOM_APOLAR, FREESASA_ATOM_POLAR, };
static struct classifier_residue protor_HIS_cfg = {
    .name = "HIS", .n_atoms = 11,
    .atom_name = (char**) protor_HIS_atom_name,
    .atom_radius = (double*) protor_HIS_atom_radius,
    .atom_class = (freesasa_atom_class*) protor_HIS_atom_class,
    .max_area = {.name = "HIS", .total = 182.97, .main_chain = 39.09, .side_chain = 143.87, .polar = 85.94, .apolar = 97.03},
};

static const char *protor_HOH_atom_name[] = {"O", };
static double protor_HOH_atom_radius[] = {1.46, };
static int protor_HOH_atom_class[] = {FREESASA_ATOM_POLAR, };
static struct classifier_residue protor_HOH_cfg = {
    .name = "HOH", .n_atoms = 1,
    .atom_name = (char**) protor_HOH_atom_name,
    .atom_radius = (double*) protor_HOH_atom_radius,
    .atom_class = (freesasa_atom_class*) protor_HOH_atom_class,
    .max_area = {NULL, 0, 0, 0, 0, 0},
};

static const char *protor_I_atom_name[] = {"O5'", "C2", "P", "C5", "N1", "C4'", "C2'", "C4", "OP2", "C3'", "C6", "O6", "N9", "OP1", "C1'", "C8", "C5'", "N7", "O3'", "O2'", "OP3", "O4'", "N3", };
static double protor_I_atom_radius[] = {1.46, 1.76, 1.8, 1.61, 1.64, 1.88, 1.88, 1.61, 1.46, 1.88, 1.61, 1.42, 1.64, 1.42, 1.88, 1.76, 1.88, 1.64, 1.46, 1.46, 1.46, 1.46, 1.64, };
static int protor_I_atom_class[] = {FREESASA_ATOM_POLAR, FREESASA_ATOM_APOLAR, FREESASA_ATOM_POLAR, FREESASA_ATOM_APOLAR, FREESASA_ATOM_POLAR, FREESASA_ATOM_APOLAR, FREESASA_ATOM_APOLAR, FREESASA_ATOM_APOLAR, FREESASA_ATOM_POLAR, FREESASA_ATOM_APOLAR, FREESASA_ATOM_APOLAR, FREESASA_ATOM_POLAR, FREESASA_ATOM_POLAR, FREESASA_ATOM_POLAR, FREESASA_ATOM_APOLAR, FREESASA_ATOM_APOLAR, FREESASA_ATOM_APOLAR, FREESASA_ATOM_POLAR, FREESASA_ATOM_POLAR, FREESASA_ATOM_POLAR, FREESASA_ATOM_POLAR, FREESASA_ATOM_POLAR, FREESASA_ATOM_POLAR, };
static struct classifier_residue protor_I_cfg = {
    .name = "I", .n_atoms = 23,
    .atom_name = (char**) protor_I_atom_name,
    .atom_radius = (double*) protor_I_atom_radius,
    .atom_class = (freesasa_atom_class*) protor_I_atom_class,
    .max_area = {NULL, 0, 0, 0, 0, 0},
};

static const char *protor_ILE_atom_name[] = {"CB", "C", "O", "N", "OXT", "CD1", "CG1", "CG2", "CA", };
static double protor_ILE_atom_radius[] = {1.88, 1.61, 1.42, 1.64, 1.46, 1.88, 1.88, 1.88, 1.88, };
static int protor_ILE_atom_class[] = {FREESASA_ATOM_APOLAR, FREESASA_ATOM_APOLAR, FREESASA_ATOM_POLAR, FREESASA_ATOM_POLAR, FREESASA_ATOM_POLAR, FREESASA_ATOM_APOLAR, FREESASA_ATOM_APOLAR, FREESASA_ATOM_APOLAR, FREESASA_ATOM_APOLAR, };
static struct classifier_residue protor_ILE_cfg = {
    .name = "ILE", .n_atoms = 9,
    .atom_name = (char**) protor_ILE_atom_name,
    .atom_radius = (double*) protor_ILE_atom_radius,
    .atom_class = (freesasa_atom_class*) protor_ILE_atom_class,
    .max_area = {.name = "ILE", .total = 175.73, .main_chain = 41.49, .side_chain = 134.23, .polar = 36.85, .apolar = 138.87},
};

static const char *protor_LEU_atom_name[] = {"CG", "CA", "CD2", "N", "CD1", "OXT", "C", "CB", "O", };
static double protor_LEU_atom_radius[] = {1.88, 1.88, 1.88, 1.64, 1.88, 1.46, 1.61, 1.88, 1.42, };
static int protor_LEU_atom_class[] = {FREESASA_ATOM_APOLAR, FREESASA_ATOM_APOLAR, FREESASA_ATOM_APOLAR, FREESASA_ATOM_POLAR, FREESASA_ATOM_APOLAR, FREESASA_ATOM_POLAR, FREESASA_ATOM_APOLAR, FREESASA_ATOM_APOLAR, FREESASA_ATOM_POLAR, };
static struct classifier_residue protor_LEU_cfg = {
    .name = "LEU", .n_atoms = 9,
    .atom_name = (char**) protor_LEU_atom_name,
    .atom_radius = (double*) protor_LEU_atom_radius,
    .atom_class = (freesasa_atom_class*) protor_LEU_atom_class,
    .max_area = {.name = "LEU", .total = 179.56, .main_chain = 39.78, .side_chain = 139.78, .polar = 37.16, .apolar = 142.39},
};

static const char *protor_LYS_atom_name[] = {"CD", "OXT", "N", "O", "C", "CB", "CE", "NZ", "CG", "CA", };
static double protor_LYS_atom_radius[] = {1.88, 1.46, 1.64, 1.42, 1.61, 1.88, 1.88, 1.64, 1.88, 1.88, };
static int protor_LYS_atom_class[] = {FREESASA_ATOM_APOLAR, FREESASA_ATOM_POLAR, FREESASA_ATOM_POLAR, FREESASA_ATOM_POLAR, FREESASA_ATOM_APOLAR, FREESASA_ATOM_APOLAR, FREESASA_ATOM_APOLAR, FREESASA_ATOM_POLAR, FREESASA_ATOM_APOLAR, FREESASA_ATOM_APOLAR, };
static struct classifier_residue protor_LYS_cfg = {
    .name = "LYS", .n_atoms = 10,
    .atom_name = (char**) protor_LYS_atom_name,
    .atom_radius = (double*) protor_LYS_atom_radius,
    .atom_class = (freesasa_atom_class*) protor_LYS_atom_class,
    .max_area = {.name = "LYS", .total = 204.98, .main_chain = 42.00, .side_chain = 162.98, .polar = 93.88, .apolar = 111.10},
};

static const char *protor_MET_atom_name[] = {"O", "CB", "C", "OXT", "N", "SD", "CE", "CA", "CG", };
static double protor_MET_atom_radius[] = {1.42, 1.88, 1.61, 1.46, 1.64, 1.77, 1.88, 1.88, 1.88, };
static int protor_MET_atom_class[] = {FREESASA_ATOM_POLAR, FREESASA_ATOM_APOLAR, FREESASA_ATOM_APOLAR, FREESASA_ATOM_POLAR, FREESASA_ATOM_POLAR, FREESASA_ATOM_POLAR, FREESASA_ATOM_APOLAR, FREESASA_ATOM_APOLAR, FREESASA_ATOM_APOLAR, };
static struct classifier_residue protor_MET_cfg = {
    .name = "MET", .n_atoms = 9,
    .atom_name = (char**) protor_MET_atom_name,
    .atom_radius = (double*) protor_MET_atom_radius,
    .atom_class = (freesasa_atom_class*) protor_MET_atom_class,
    .max_area = {.name = "MET", .total = 193.10, .main_chain = 42.00, .side_chain = 151.10, .polar = 75.48, .apolar = 117.62},
};

static const char *protor_NH2_atom_name[] = {"N", };
static double protor_NH2_atom_radius[] = {1.64, };
static int protor_NH2_atom_class[] = {FREESASA_ATOM_POLAR, };
static struct classifier_residue protor_NH2_cfg = {
    .name = "NH2", .n_atoms = 1,
    .atom_name = (char**) protor_NH2_atom_name,
    .atom_radius = (double*) protor_NH2_atom_radius,
    .atom_class = (freesasa_atom_class*) protor_NH2_atom_class,
    .max_area = {NULL, 0, 0, 0, 0, 0},
};

static const char *protor_PHE_atom_name[] = {"O", "C", "CB", "CD1", "CZ", "OXT", "CE1", "N", "CE2", "CD2", "CA", "CG", };
static double protor_PHE_atom_radius[] = {1.42, 1.61, 1.88, 1.76, 1.76, 1.46, 1.76, 1.64, 1.76, 1.76, 1.88, 1.61, };
static int protor_PHE_atom_class[] = {FREESASA_ATOM_POLAR, FREESASA_ATOM_APOLAR, FREESASA_ATOM_APOLAR, FREESASA_ATOM_APOLAR, FREESASA_ATOM_APOLAR, FREESASA_ATOM_POLAR, FREESASA_ATOM_APOLAR, FREESASA_ATOM_POLAR, FREESASA_ATOM_APOLAR, FREESASA_ATOM_APOLAR, FREESASA_ATOM_APOLAR, FREESASA_ATOM_APOLAR, };
static struct classifier_residue protor_PHE_cfg = {
    .name = "PHE", .n_atoms = 12,
    .atom_name = (char**) protor_PHE_atom_name,
    .atom_radius = (double*) protor_PHE_atom_radius,
    .atom_class = (freesasa_atom_class*) protor_PHE_atom_class,
    .max_area = {.name = "PHE", .total = 199.88, .main_chain = 38.43, .side_chain = 161.45, .polar = 34.94, .apolar = 164.94},
};

static const char *protor_PRO_atom_name[] = {"O", "CB", "C", "OXT", "CD", "N", "CG", "CA", };
static double protor_PRO_atom_radius[] = {1.42, 1.88, 1.61, 1.46, 1.88, 1.64, 1.88, 1.88, };
static int protor_PRO_atom_class[] = {FREESASA_ATOM_POLAR, FREESASA_ATOM_APOLAR, FREESASA_ATOM_APOLAR, FREESASA_ATOM_POLAR, FREESASA_ATOM_APOLAR, FREESASA_ATOM_POLAR, FREESASA_ATOM_APOLAR, FREESASA_ATOM_APOLAR, };
static struct classifier_residue protor_PRO_cfg = {
    .name = "PRO", .n_atoms = 8,
    .atom_name = (char**) protor_PRO_atom_name,
    .atom_radius = (double*) protor_PRO_atom_radius,
    .atom_class = (freesasa_atom_class*) protor_PRO_atom_class,
    .max_area = {.name = "PRO", .total = 137.21, .main_chain = 27.51, .side_chain = 109.70, .polar = 16.09, .apolar = 121.12},
};

static const char *protor_PYL_atom_name[] = {"CD2", "NZ", "CA", "CG", "N2", "CD", "OXT", "O", "C", "CE", "CB2", "CG2", "CE2", "N", "CA2", "CB", "C2", "O2", };
static double protor_PYL_atom_radius[] = {1.88, 1.64, 1.88, 1.88, 1.64, 1.88, 1.46, 1.42, 1.61, 1.88, 1.88, 1.88, 1.76, 1.64, 1.88, 1.88, 1.61, 1.42, };
static int protor_PYL_atom_class[] = {FREESASA_ATOM_APOLAR, FREESASA_ATOM_POLAR, FREESASA_ATOM_APOLAR, FREESASA_ATOM_APOLAR, FREESASA_ATOM_POLAR, FREESASA_ATOM_APOLAR, FREESASA_ATOM_POLAR, FREESASA_ATOM_POLAR, FREESASA_ATOM_APOLAR, FREESASA_ATOM_APOLAR, FREESASA_ATOM_APOLAR, FREESASA_ATOM_APOLAR, FREESASA_ATOM_APOLAR, FREESASA_ATOM_POLAR, FREESASA_ATOM_APOLAR, FREESASA_ATOM_APOLAR, FREESASA_ATOM_APOLAR, FREESASA_ATOM_POLAR, };
static struct classifier_residue protor_PYL_cfg = {
    .name = "PYL", .n_atoms = 18,
    .atom_name = (char**) protor_PYL_atom_name,
    .atom_radius = (double*) protor_PYL_atom_radius,
    .atom_class = (freesasa_atom_class*) protor_PYL_atom_class,
    .max_area = {NULL, 0, 0, 0, 0, 0},
};

static const char *protor_SEC_atom_name[] = {"OXT", "N", "CA", "O", "SE", "CB", "C", };
static double protor_SEC_atom_radius[] = {1.46, 1.64, 1.88, 1.42, 1.9, 1.88, 1.61, };
static int protor_SEC_atom_class[] = {FREESASA_ATOM_POLAR, FREESASA_ATOM_POLAR, FREESASA_ATOM_APOLAR, FREESASA_ATOM_POLAR, FREESASA_ATOM_POLAR, FREESASA_ATOM_APOLAR, FREESASA_ATOM_APOLAR, };
static struct classifier_residue protor_SEC_cfg = {
    .name = "SEC", .n_atoms = 7,
    .atom_name = (char**) protor_SEC_atom_name,
    .atom_radius = (double*) protor_SEC_atom_radius,
    .atom_class = (freesasa_atom_class*) protor_SEC_atom_class,
    .max_area = {NULL, 0, 0, 0, 0, 0},
};

static const char *protor_SER_atom_name[] = {"OXT", "N", "CA", "O", "OG", "C", "CB", };
static double protor_SER_atom_radius[] = {1.46, 1.64, 1.88, 1.42, 1.46, 1.61, 1.88, };
static int protor_SER_atom_class[] = {FREESASA_ATOM_POLAR, FREESASA_ATOM_POLAR, FREESASA_ATOM_APOLAR, FREESASA_ATOM_POLAR, FREESASA_ATOM_POLAR, FREESASA_ATOM_APOLAR, FREESASA_ATOM_APOLAR, };
static struct classifier_residue protor_SER_cfg = {
    .name = "SER", .n_atoms = 7,
    .atom_name = (char**) protor_SER_atom_name,
    .atom_radius = (double*) protor_SER_atom_radius,
    .atom_class = (freesasa_atom_class*) protor_SER_atom_class,
    .max_area = {.name = "SER", .total = 118.34, .main_chain = 43.41, .side_chain = 74.93, .polar = 71.38, .apolar = 46.96},
};

static const char *protor_T_atom_name[] = {"C5'", "O3'", "OP1", "C6", "C1'", "O4", "N3", "OP3", "C7", "O4'", "C5", "O5'", "O2", "C2", "P", "C4", "OP2", "C3'", "N1", "C2'", "C4'", };
static double protor_T_atom_radius[] = {1.88, 1.46, 1.42, 1.76, 1.88, 1.42, 1.64, 1.46, 1.88, 1.46, 1.61, 1.46, 1.42, 1.61, 1.8, 1.61, 1.46, 1.88, 1.64, 1.88, 1.88, };
static int protor_T_atom_class[] = {FREESASA_ATOM_APOLAR, FREESASA_ATOM_POLAR, FREESASA_ATOM_POLAR, FREESASA_ATOM_APOLAR, FREESASA_ATOM_APOLAR, FREESASA_ATOM_POLAR, FREESASA_ATOM_POLAR, FREESASA_ATOM_POLAR, FREESASA_ATOM_APOLAR, FREESASA_ATOM_POLAR, FREESASA_ATOM_APOLAR, FREESASA_ATOM_POLAR, FREESASA_ATOM_POLAR, FREESASA_ATOM_APOLAR, FREESASA_ATOM_POLAR, FREESASA_ATOM_APOLAR, FREESASA_ATOM_POLAR, FREESASA_ATOM_APOLAR, FREESASA_ATOM_POLAR, FREESASA_ATOM_APOLAR, FREESASA_ATOM_APOLAR, };
static struct classifier_residue protor_T_cfg = {
    .name = "T", .n_atoms = 21,
    .atom_name = (char**) protor_T_atom_name,
    .atom_radius = (double*) protor_T_atom_radius,
    .atom_class = (freesasa_atom_class*) protor_T_atom_class,
    .max_area = {NULL, 0, 0, 0, 0, 0},
};

static const char *protor_THR_atom_name[] = {"CG2", "CA", "C", "CB", "O", "N", "OXT", "OG1", };
static double protor_THR_atom_radius[] = {1.88, 1.88, 1.61, 1.88, 1.42, 1.64, 1.46, 1.46, };
static int protor_THR_atom_class[] = {FREESASA_ATOM_APOLAR, FREESASA_ATOM_APOLAR, FREESASA_ATOM_APOLAR, FREESASA_ATOM_APOLAR, FREESASA_ATOM_POLAR, FREESASA_ATOM_POLAR, FREESASA_ATOM_POLAR, FREESASA_ATOM_POLAR, };
static struct classifier_residue protor_THR_cfg = {
    .name = "THR", .n_atoms = 8,
    .atom_name = (char**) protor_THR_atom_name,
    .atom_radius = (double*) protor_THR_atom_radius,
    .atom_class = (freesasa_atom_class*) protor_THR_atom_class,
    .max_area = {.name = "THR", .total = 140.60, .main_chain = 41.96, .side_chain = 98.64, .polar = 66.15, .apolar = 74.45},
};

static const char *protor_TRP_atom_name[] = {"N", "CD1", "OXT", "CZ2", "C", "CB", "NE1", "O", "CG", "CA", "CH2", "CD2", "CZ3", "CE2", "CE3", };
static double protor_TRP_atom_radius[] = {1.64, 1.76, 1.46, 1.76, 1.61, 1.88, 1.64, 1.42, 1.61, 1.88, 1.76, 1.61, 1.76, 1.61, 1.76, };
static int protor_TRP_atom_class[] = {FREESASA_ATOM_POLAR, FREESASA_ATOM_APOLAR, FREESASA_ATOM_POLAR, FREESASA_ATOM_APOLAR, FREESASA_ATOM_APOLAR, FREESASA_ATOM_APOLAR, FREESASA_ATOM_POLAR, FREESASA_ATOM_POLAR, FREESASA_ATOM_APOLAR, FREESASA_ATOM_APOLAR, FREESASA_ATOM_APOLAR, FREESASA_ATOM_APOLAR, FREESASA_ATOM_APOLAR, FREESASA_ATOM_APOLAR, FREESASA_ATOM_APOLAR, };
static struct classifier_residue protor_TRP_cfg = {
    .name = "TRP", .n_atoms = 15,
    .atom_name = (char**) protor_TRP_atom_name,
    .atom_radius = (double*) protor_TRP_atom_radius,
    .atom_class = (freesasa_atom_class*) protor_TRP_atom_class,
    .max_area = {.name = "TRP", .total = 249.19, .main_chain = 42.59, .side_chain = 206.60, .polar = 61.64, .apolar = 187.55},
};

static const char *protor_TYR_atom_name[] = {"CB", "C", "O", "N", "OH", "OXT", "CE1", "CD1", "CZ", "CE2", "CG", "CA", "CD2", };
static double protor_TYR_atom_radius[] = {1.88, 1.61, 1.42, 1.64, 1.46, 1.46, 1.76, 1.76, 1.61, 1.76, 1.61, 1.88, 1.76, };
static int protor_TYR_atom_class[] = {FREESASA_ATOM_APOLAR, FREESASA_ATOM_APOLAR, FREESASA_ATOM_POLAR, FREESASA_ATOM_POLAR, FREESASA_ATOM_POLAR, FREESASA_ATOM_POLAR, FREESASA_ATOM_APOLAR, FREESASA_ATOM_APOLAR, FREESASA_ATOM_APOLAR, FREESASA_ATOM_APOLAR, FREESASA_ATOM_APOLAR, FREESASA_ATOM_APOLAR, FREESASA_ATOM_APOLAR, };
static struct classifier_residue protor_TYR_cfg = {
    .name = "TYR", .n_atoms = 13,
    .atom_name = (char**) protor_TYR_atom_name,
    .atom_radius = (double*) protor_TYR_atom_radius,
    .atom_class = (freesasa_atom_class*) protor_TYR_atom_class,
    .max_area = {.name = "TYR", .total = 214.19, .main_chain = 38.43, .side_chain = 175.76, .polar = 81.12, .apolar = 133.07},
};

static const char *protor_U_atom_name[] = {"C5", "O2", "C2", "P", "O5'", "OP2", "C3'", "C4", "C4'", "C2'", "N1", "O3'", "C5'", "C6", "OP1", "C1'", "O4", "N3", "O4'", "OP3", "O2'", };
static double protor_U_atom_radius[] = {1.76, 1.42, 1.61, 1.8, 1.46, 1.46, 1.88, 1.61, 1.88, 1.88, 1.64, 1.46, 1.88, 1.76, 1.42, 1.88, 1.42, 1.64, 1.46, 1.46, 1.46, };
static int protor_U_atom_class[] = {FREESASA_ATOM_APOLAR, FREESASA_ATOM_POLAR, FREESASA_ATOM_APOLAR, FREESASA_ATOM_POLAR, FREESASA_ATOM_POLAR, FREESASA_ATOM_POLAR, FREESASA_ATOM_APOLAR, FREESASA_ATOM_APOLAR, FREESASA_ATOM_APOLAR, FREESASA_ATOM_APOLAR, FREESASA_ATOM_POLAR, FREESASA_ATOM_POLAR, FREESASA_ATOM_APOLAR, FREESASA_ATOM_APOLAR, FREESASA_ATOM_POLAR, FREESASA_ATOM_APOLAR, FREESASA_ATOM_POLAR, FREESASA_ATOM_POLAR, FREESASA_ATOM_POLAR, FREESASA_ATOM_POLAR, FREESASA_ATOM_POLAR, };
static struct classifier_residue protor_U_cfg = {
    .name = "U", .n_atoms = 21,
    .atom_name = (char**) protor_U_atom_name,
    .atom_radius = (double*) protor_U_atom_radius,
    .atom_class = (freesasa_atom_class*) protor_U_atom_class,
    .max_area = {NULL, 0, 0, 0, 0, 0},
};

static const char *protor_VAL_atom_name[] = {"N", "OXT", "CB", "C", "O", "CA", "CG2", "CG1", };
static double protor_VAL_atom_radius[] = {1.64, 1.46, 1.88, 1.61, 1.42, 1.88, 1.88, 1.88, };
static int protor_VAL_atom_class[] = {FREESASA_ATOM_POLAR, FREESASA_ATOM_POLAR, FREESASA_ATOM_APOLAR, FREESASA_ATOM_APOLAR, FREESASA_ATOM_POLAR, FREESASA_ATOM_APOLAR, FREESASA_ATOM_APOLAR, FREESASA_ATOM_APOLAR, };
static struct classifier_residue protor_VAL_cfg = {
    .name = "VAL", .n_atoms = 8,
    .atom_name = (char**) protor_VAL_atom_name,
    .atom_radius = (double*) protor_VAL_atom_radius,
    .atom_class = (freesasa_atom_class*) protor_VAL_atom_class,
    .max_area = {.name = "VAL", .total = 151.97, .main_chain = 41.50, .side_chain = 110.46, .polar = 36.87, .apolar = 115.09},
};

static struct classifier_residue *protor_residue_cfg[] = {
    &protor_A_cfg, &protor_ACE_cfg, &protor_ALA_cfg, &protor_ARG_cfg, &protor_ASN_cfg, &protor_ASP_cfg, &protor_ASX_cfg, &protor_C_cfg, &protor_CYS_cfg, &protor_DA_cfg, &protor_DC_cfg, &protor_DG_cfg, &protor_DI_cfg, &protor_DT_cfg, &protor_DU_cfg, &protor_G_cfg, &protor_GLN_cfg, &protor_GLU_cfg, &protor_GLX_cfg, &protor_GLY_cfg, &protor_HIS_cfg, &protor_HOH_cfg, &protor_I_cfg, &protor_ILE_cfg, &protor_LEU_cfg, &protor_LYS_cfg, &protor_MET_cfg, &protor_NH2_cfg, &protor_PHE_cfg, &protor_PRO_cfg, &protor_PYL_cfg, &protor_SEC_cfg, &protor_SER_cfg, &protor_T_cfg, &protor_THR_cfg, &protor_TRP_cfg, &protor_TYR_cfg, &protor_U_cfg, &protor_VAL_cfg, };

const freesasa_classifier freesasa_protor_classifier = {
    .n_residues = 39,    .residue_name = (char**) protor_residue_name,
    .residue = (struct classifier_residue **) protor_residue_cfg,
    .name = "ProtOr",
};

