#include "classifier.h"

/* Autogenerated code from the script config2c.pl */

static const char *naccess_residue_name[] = {"A", "ANY", "ARG", "ASN", "ASP", "C", "CYS", "DA", "DC", "DG", "DI", "DT", "DU", "G", "GLN", "GLU", "HIS", "I", "ILE", "LEU", "LYS", "MET", "PHE", "PRO", "SEC", "SER", "T", "THR", "TRP", "TYR", "U", "VAL", };
static const char *naccess_class_name[] = {"apolar", "polar", };

static const char *naccess_A_atom_name[] = {"N1", "C6", "N6", "C5", "N9", "N3", "N7", "C4", "C8", "C2", };
static double naccess_A_atom_radius[] = {1.60, 1.80, 1.60, 1.80, 1.60, 1.60, 1.60, 1.80, 1.80, 1.80, };
static int naccess_A_atom_class[] = {1, 0, 1, 0, 1, 1, 1, 0, 0, 0, };
static struct classifier_residue naccess_A_cfg = {
    .name = "A", .n_atoms = 10,
    .atom_name = (char**) naccess_A_atom_name,
    .atom_radius = (double*) naccess_A_atom_radius,
    .atom_class = (int*) naccess_A_atom_class };

static const char *naccess_ANY_atom_name[] = {"OP1", "N", "CB", "C3'", "C", "CA", "O", "C1'", "P", "O4'", "O3'", "OP2", "C5'", "C2'", "C4'", "O5'", "OP3", "O2'", "OXT", };
static double naccess_ANY_atom_radius[] = {1.40, 1.65, 1.87, 1.80, 1.76, 1.87, 1.40, 1.80, 1.90, 1.40, 1.40, 1.40, 1.80, 1.80, 1.80, 1.40, 1.40, 1.40, 1.40, };
static int naccess_ANY_atom_class[] = {1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, };
static struct classifier_residue naccess_ANY_cfg = {
    .name = "ANY", .n_atoms = 19,
    .atom_name = (char**) naccess_ANY_atom_name,
    .atom_radius = (double*) naccess_ANY_atom_radius,
    .atom_class = (int*) naccess_ANY_atom_class };

static const char *naccess_ARG_atom_name[] = {"CD", "CZ", "NE", "CG", "NH2", "NH1", };
static double naccess_ARG_atom_radius[] = {1.87, 1.76, 1.65, 1.87, 1.65, 1.65, };
static int naccess_ARG_atom_class[] = {0, 0, 1, 0, 1, 1, };
static struct classifier_residue naccess_ARG_cfg = {
    .name = "ARG", .n_atoms = 6,
    .atom_name = (char**) naccess_ARG_atom_name,
    .atom_radius = (double*) naccess_ARG_atom_radius,
    .atom_class = (int*) naccess_ARG_atom_class };

static const char *naccess_ASN_atom_name[] = {"OD1", "CG", "ND2", };
static double naccess_ASN_atom_radius[] = {1.40, 1.76, 1.65, };
static int naccess_ASN_atom_class[] = {1, 0, 1, };
static struct classifier_residue naccess_ASN_cfg = {
    .name = "ASN", .n_atoms = 3,
    .atom_name = (char**) naccess_ASN_atom_name,
    .atom_radius = (double*) naccess_ASN_atom_radius,
    .atom_class = (int*) naccess_ASN_atom_class };

static const char *naccess_ASP_atom_name[] = {"OD2", "OD1", "CG", };
static double naccess_ASP_atom_radius[] = {1.40, 1.40, 1.76, };
static int naccess_ASP_atom_class[] = {1, 1, 0, };
static struct classifier_residue naccess_ASP_cfg = {
    .name = "ASP", .n_atoms = 3,
    .atom_name = (char**) naccess_ASP_atom_name,
    .atom_radius = (double*) naccess_ASP_atom_radius,
    .atom_class = (int*) naccess_ASP_atom_class };

static const char *naccess_C_atom_name[] = {"C6", "N1", "C5", "N3", "O2", "C4", "C2", "N4", };
static double naccess_C_atom_radius[] = {1.80, 1.60, 1.80, 1.60, 1.40, 1.80, 1.80, 1.60, };
static int naccess_C_atom_class[] = {0, 1, 0, 1, 1, 0, 0, 1, };
static struct classifier_residue naccess_C_cfg = {
    .name = "C", .n_atoms = 8,
    .atom_name = (char**) naccess_C_atom_name,
    .atom_radius = (double*) naccess_C_atom_radius,
    .atom_class = (int*) naccess_C_atom_class };

static const char *naccess_CYS_atom_name[] = {"SG", };
static double naccess_CYS_atom_radius[] = {1.85, };
static int naccess_CYS_atom_class[] = {0, };
static struct classifier_residue naccess_CYS_cfg = {
    .name = "CYS", .n_atoms = 1,
    .atom_name = (char**) naccess_CYS_atom_name,
    .atom_radius = (double*) naccess_CYS_atom_radius,
    .atom_class = (int*) naccess_CYS_atom_class };

static const char *naccess_DA_atom_name[] = {"N1", "C6", "N6", "C5", "N9", "N3", "N7", "C4", "C8", "C2", };
static double naccess_DA_atom_radius[] = {1.60, 1.80, 1.60, 1.80, 1.60, 1.60, 1.60, 1.80, 1.80, 1.80, };
static int naccess_DA_atom_class[] = {1, 0, 1, 0, 1, 1, 1, 0, 0, 0, };
static struct classifier_residue naccess_DA_cfg = {
    .name = "DA", .n_atoms = 10,
    .atom_name = (char**) naccess_DA_atom_name,
    .atom_radius = (double*) naccess_DA_atom_radius,
    .atom_class = (int*) naccess_DA_atom_class };

static const char *naccess_DC_atom_name[] = {"C6", "N1", "C5", "N3", "O2", "C4", "C2", "N4", };
static double naccess_DC_atom_radius[] = {1.80, 1.60, 1.80, 1.60, 1.40, 1.80, 1.80, 1.60, };
static int naccess_DC_atom_class[] = {0, 1, 0, 1, 1, 0, 0, 1, };
static struct classifier_residue naccess_DC_cfg = {
    .name = "DC", .n_atoms = 8,
    .atom_name = (char**) naccess_DC_atom_name,
    .atom_radius = (double*) naccess_DC_atom_radius,
    .atom_class = (int*) naccess_DC_atom_class };

static const char *naccess_DG_atom_name[] = {"N1", "C6", "C5", "N9", "N3", "N2", "N7", "C4", "C8", "O6", "C2", };
static double naccess_DG_atom_radius[] = {1.60, 1.80, 1.80, 1.60, 1.60, 1.60, 1.60, 1.80, 1.80, 1.40, 1.80, };
static int naccess_DG_atom_class[] = {1, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, };
static struct classifier_residue naccess_DG_cfg = {
    .name = "DG", .n_atoms = 11,
    .atom_name = (char**) naccess_DG_atom_name,
    .atom_radius = (double*) naccess_DG_atom_radius,
    .atom_class = (int*) naccess_DG_atom_class };

static const char *naccess_DI_atom_name[] = {"N1", "C6", "C5", "N9", "N3", "N7", "C4", "C8", "O6", "C2", };
static double naccess_DI_atom_radius[] = {1.60, 1.80, 1.80, 1.60, 1.60, 1.60, 1.80, 1.80, 1.40, 1.80, };
static int naccess_DI_atom_class[] = {1, 0, 0, 1, 1, 1, 0, 0, 1, 0, };
static struct classifier_residue naccess_DI_cfg = {
    .name = "DI", .n_atoms = 10,
    .atom_name = (char**) naccess_DI_atom_name,
    .atom_radius = (double*) naccess_DI_atom_radius,
    .atom_class = (int*) naccess_DI_atom_class };

static const char *naccess_DT_atom_name[] = {"C6", "N1", "C5", "N3", "O2", "C7", "C4", "O4", "C2", };
static double naccess_DT_atom_radius[] = {1.80, 1.60, 1.80, 1.60, 1.40, 1.80, 1.80, 1.40, 1.80, };
static int naccess_DT_atom_class[] = {0, 1, 0, 1, 1, 0, 0, 1, 0, };
static struct classifier_residue naccess_DT_cfg = {
    .name = "DT", .n_atoms = 9,
    .atom_name = (char**) naccess_DT_atom_name,
    .atom_radius = (double*) naccess_DT_atom_radius,
    .atom_class = (int*) naccess_DT_atom_class };

static const char *naccess_DU_atom_name[] = {"C6", "N1", "C5", "N3", "O2", "C4", "O4", "C2", };
static double naccess_DU_atom_radius[] = {1.80, 1.60, 1.80, 1.60, 1.40, 1.80, 1.40, 1.80, };
static int naccess_DU_atom_class[] = {0, 1, 0, 1, 1, 0, 1, 0, };
static struct classifier_residue naccess_DU_cfg = {
    .name = "DU", .n_atoms = 8,
    .atom_name = (char**) naccess_DU_atom_name,
    .atom_radius = (double*) naccess_DU_atom_radius,
    .atom_class = (int*) naccess_DU_atom_class };

static const char *naccess_G_atom_name[] = {"N1", "C6", "C5", "N9", "N3", "N2", "N7", "C4", "C8", "O6", "C2", };
static double naccess_G_atom_radius[] = {1.60, 1.80, 1.80, 1.60, 1.60, 1.60, 1.60, 1.80, 1.80, 1.40, 1.80, };
static int naccess_G_atom_class[] = {1, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, };
static struct classifier_residue naccess_G_cfg = {
    .name = "G", .n_atoms = 11,
    .atom_name = (char**) naccess_G_atom_name,
    .atom_radius = (double*) naccess_G_atom_radius,
    .atom_class = (int*) naccess_G_atom_class };

static const char *naccess_GLN_atom_name[] = {"CD", "NE2", "OE1", "CG", };
static double naccess_GLN_atom_radius[] = {1.76, 1.65, 1.40, 1.87, };
static int naccess_GLN_atom_class[] = {0, 1, 1, 0, };
static struct classifier_residue naccess_GLN_cfg = {
    .name = "GLN", .n_atoms = 4,
    .atom_name = (char**) naccess_GLN_atom_name,
    .atom_radius = (double*) naccess_GLN_atom_radius,
    .atom_class = (int*) naccess_GLN_atom_class };

static const char *naccess_GLU_atom_name[] = {"OE2", "CD", "OE1", "CG", };
static double naccess_GLU_atom_radius[] = {1.40, 1.76, 1.40, 1.87, };
static int naccess_GLU_atom_class[] = {1, 0, 1, 0, };
static struct classifier_residue naccess_GLU_cfg = {
    .name = "GLU", .n_atoms = 4,
    .atom_name = (char**) naccess_GLU_atom_name,
    .atom_radius = (double*) naccess_GLU_atom_radius,
    .atom_class = (int*) naccess_GLU_atom_class };

static const char *naccess_HIS_atom_name[] = {"CD2", "NE2", "CE1", "CG", "ND1", };
static double naccess_HIS_atom_radius[] = {1.76, 1.65, 1.76, 1.76, 1.65, };
static int naccess_HIS_atom_class[] = {0, 1, 0, 0, 1, };
static struct classifier_residue naccess_HIS_cfg = {
    .name = "HIS", .n_atoms = 5,
    .atom_name = (char**) naccess_HIS_atom_name,
    .atom_radius = (double*) naccess_HIS_atom_radius,
    .atom_class = (int*) naccess_HIS_atom_class };

static const char *naccess_I_atom_name[] = {"N1", "C6", "C5", "N9", "N3", "N7", "C4", "C8", "O6", "C2", };
static double naccess_I_atom_radius[] = {1.60, 1.80, 1.80, 1.60, 1.60, 1.60, 1.80, 1.80, 1.40, 1.80, };
static int naccess_I_atom_class[] = {1, 0, 0, 1, 1, 1, 0, 0, 1, 0, };
static struct classifier_residue naccess_I_cfg = {
    .name = "I", .n_atoms = 10,
    .atom_name = (char**) naccess_I_atom_name,
    .atom_radius = (double*) naccess_I_atom_radius,
    .atom_class = (int*) naccess_I_atom_class };

static const char *naccess_ILE_atom_name[] = {"CD1", "CG2", "CG1", };
static double naccess_ILE_atom_radius[] = {1.87, 1.87, 1.87, };
static int naccess_ILE_atom_class[] = {0, 0, 0, };
static struct classifier_residue naccess_ILE_cfg = {
    .name = "ILE", .n_atoms = 3,
    .atom_name = (char**) naccess_ILE_atom_name,
    .atom_radius = (double*) naccess_ILE_atom_radius,
    .atom_class = (int*) naccess_ILE_atom_class };

static const char *naccess_LEU_atom_name[] = {"CD2", "CD1", "CG", };
static double naccess_LEU_atom_radius[] = {1.87, 1.87, 1.87, };
static int naccess_LEU_atom_class[] = {0, 0, 0, };
static struct classifier_residue naccess_LEU_cfg = {
    .name = "LEU", .n_atoms = 3,
    .atom_name = (char**) naccess_LEU_atom_name,
    .atom_radius = (double*) naccess_LEU_atom_radius,
    .atom_class = (int*) naccess_LEU_atom_class };

static const char *naccess_LYS_atom_name[] = {"CD", "CG", "CE", "NZ", };
static double naccess_LYS_atom_radius[] = {1.87, 1.87, 1.87, 1.50, };
static int naccess_LYS_atom_class[] = {0, 0, 0, 1, };
static struct classifier_residue naccess_LYS_cfg = {
    .name = "LYS", .n_atoms = 4,
    .atom_name = (char**) naccess_LYS_atom_name,
    .atom_radius = (double*) naccess_LYS_atom_radius,
    .atom_class = (int*) naccess_LYS_atom_class };

static const char *naccess_MET_atom_name[] = {"CG", "CE", "SD", };
static double naccess_MET_atom_radius[] = {1.87, 1.87, 1.85, };
static int naccess_MET_atom_class[] = {0, 0, 0, };
static struct classifier_residue naccess_MET_cfg = {
    .name = "MET", .n_atoms = 3,
    .atom_name = (char**) naccess_MET_atom_name,
    .atom_radius = (double*) naccess_MET_atom_radius,
    .atom_class = (int*) naccess_MET_atom_class };

static const char *naccess_PHE_atom_name[] = {"CD2", "CD1", "CZ", "CE1", "CG", "CE2", };
static double naccess_PHE_atom_radius[] = {1.76, 1.76, 1.76, 1.76, 1.76, 1.76, };
static int naccess_PHE_atom_class[] = {0, 0, 0, 0, 0, 0, };
static struct classifier_residue naccess_PHE_cfg = {
    .name = "PHE", .n_atoms = 6,
    .atom_name = (char**) naccess_PHE_atom_name,
    .atom_radius = (double*) naccess_PHE_atom_radius,
    .atom_class = (int*) naccess_PHE_atom_class };

static const char *naccess_PRO_atom_name[] = {"CD", "CG", };
static double naccess_PRO_atom_radius[] = {1.87, 1.87, };
static int naccess_PRO_atom_class[] = {0, 0, };
static struct classifier_residue naccess_PRO_cfg = {
    .name = "PRO", .n_atoms = 2,
    .atom_name = (char**) naccess_PRO_atom_name,
    .atom_radius = (double*) naccess_PRO_atom_radius,
    .atom_class = (int*) naccess_PRO_atom_class };

static const char *naccess_SEC_atom_name[] = {"SE", };
static double naccess_SEC_atom_radius[] = {1.80, };
static int naccess_SEC_atom_class[] = {0, };
static struct classifier_residue naccess_SEC_cfg = {
    .name = "SEC", .n_atoms = 1,
    .atom_name = (char**) naccess_SEC_atom_name,
    .atom_radius = (double*) naccess_SEC_atom_radius,
    .atom_class = (int*) naccess_SEC_atom_class };

static const char *naccess_SER_atom_name[] = {"OG", };
static double naccess_SER_atom_radius[] = {1.40, };
static int naccess_SER_atom_class[] = {1, };
static struct classifier_residue naccess_SER_cfg = {
    .name = "SER", .n_atoms = 1,
    .atom_name = (char**) naccess_SER_atom_name,
    .atom_radius = (double*) naccess_SER_atom_radius,
    .atom_class = (int*) naccess_SER_atom_class };

static const char *naccess_T_atom_name[] = {"C6", "N1", "C5", "N3", "O2", "C7", "C4", "O4", "C2", };
static double naccess_T_atom_radius[] = {1.80, 1.60, 1.80, 1.60, 1.40, 1.80, 1.80, 1.40, 1.80, };
static int naccess_T_atom_class[] = {0, 1, 0, 1, 1, 0, 0, 1, 0, };
static struct classifier_residue naccess_T_cfg = {
    .name = "T", .n_atoms = 9,
    .atom_name = (char**) naccess_T_atom_name,
    .atom_radius = (double*) naccess_T_atom_radius,
    .atom_class = (int*) naccess_T_atom_class };

static const char *naccess_THR_atom_name[] = {"CG2", "OG1", };
static double naccess_THR_atom_radius[] = {1.87, 1.40, };
static int naccess_THR_atom_class[] = {0, 1, };
static struct classifier_residue naccess_THR_cfg = {
    .name = "THR", .n_atoms = 2,
    .atom_name = (char**) naccess_THR_atom_name,
    .atom_radius = (double*) naccess_THR_atom_radius,
    .atom_class = (int*) naccess_THR_atom_class };

static const char *naccess_TRP_atom_name[] = {"CZ2", "CE2", "NE1", "CD1", "CD2", "CH2", "CG", "CE3", "CZ3", };
static double naccess_TRP_atom_radius[] = {1.76, 1.76, 1.65, 1.76, 1.76, 1.76, 1.76, 1.76, 1.76, };
static int naccess_TRP_atom_class[] = {0, 0, 1, 0, 0, 0, 0, 0, 0, };
static struct classifier_residue naccess_TRP_cfg = {
    .name = "TRP", .n_atoms = 9,
    .atom_name = (char**) naccess_TRP_atom_name,
    .atom_radius = (double*) naccess_TRP_atom_radius,
    .atom_class = (int*) naccess_TRP_atom_class };

static const char *naccess_TYR_atom_name[] = {"CD2", "CD1", "CZ", "CE1", "CG", "OH", "CE2", };
static double naccess_TYR_atom_radius[] = {1.76, 1.76, 1.76, 1.76, 1.76, 1.40, 1.76, };
static int naccess_TYR_atom_class[] = {0, 0, 0, 0, 0, 1, 0, };
static struct classifier_residue naccess_TYR_cfg = {
    .name = "TYR", .n_atoms = 7,
    .atom_name = (char**) naccess_TYR_atom_name,
    .atom_radius = (double*) naccess_TYR_atom_radius,
    .atom_class = (int*) naccess_TYR_atom_class };

static const char *naccess_U_atom_name[] = {"C6", "N1", "C5", "N3", "O2", "C4", "O4", "C2", };
static double naccess_U_atom_radius[] = {1.80, 1.60, 1.80, 1.60, 1.40, 1.80, 1.40, 1.80, };
static int naccess_U_atom_class[] = {0, 1, 0, 1, 1, 0, 1, 0, };
static struct classifier_residue naccess_U_cfg = {
    .name = "U", .n_atoms = 8,
    .atom_name = (char**) naccess_U_atom_name,
    .atom_radius = (double*) naccess_U_atom_radius,
    .atom_class = (int*) naccess_U_atom_class };

static const char *naccess_VAL_atom_name[] = {"CG2", "CG1", };
static double naccess_VAL_atom_radius[] = {1.87, 1.87, };
static int naccess_VAL_atom_class[] = {0, 0, };
static struct classifier_residue naccess_VAL_cfg = {
    .name = "VAL", .n_atoms = 2,
    .atom_name = (char**) naccess_VAL_atom_name,
    .atom_radius = (double*) naccess_VAL_atom_radius,
    .atom_class = (int*) naccess_VAL_atom_class };

static struct classifier_residue *naccess_residue_cfg[] = {
    &naccess_A_cfg, &naccess_ANY_cfg, &naccess_ARG_cfg, &naccess_ASN_cfg, &naccess_ASP_cfg, &naccess_C_cfg, &naccess_CYS_cfg, &naccess_DA_cfg, &naccess_DC_cfg, &naccess_DG_cfg, &naccess_DI_cfg, &naccess_DT_cfg, &naccess_DU_cfg, &naccess_G_cfg, &naccess_GLN_cfg, &naccess_GLU_cfg, &naccess_HIS_cfg, &naccess_I_cfg, &naccess_ILE_cfg, &naccess_LEU_cfg, &naccess_LYS_cfg, &naccess_MET_cfg, &naccess_PHE_cfg, &naccess_PRO_cfg, &naccess_SEC_cfg, &naccess_SER_cfg, &naccess_T_cfg, &naccess_THR_cfg, &naccess_TRP_cfg, &naccess_TYR_cfg, &naccess_U_cfg, &naccess_VAL_cfg, };

static struct classifier_config naccess_auto_config = {
    .n_residues = 32, .n_classes = 2,
    .residue_name = (char**) naccess_residue_name,
    .class_name = (char**) naccess_class_name,
    .residue = (struct classifier_residue **) naccess_residue_cfg
};

static void naccess_dummy_free(void *arg) {}

const freesasa_classifier freesasa_naccess_classifier = {
    .config = &naccess_auto_config,
    .n_classes = 2,
    .radius = freesasa_classifier_config_radius,
    .sasa_class =freesasa_classifier_config_class,
    .class2str = freesasa_classifier_config_class2str,
    // Since this object is const, calling free should emit compiler warnings.
    .free_config = naccess_dummy_free,
};
