#include "classifier.h"

/* Autogenerated code from the script config2c.pl */

static const char *oons_residue_name[] = {"ACE", "ANY", "ARG", "ASN", "ASP", "ASX", "CSE", "CYS", "GLN", "GLU", "GLX", "HIS", "HOH", "ILE", "LEU", "LYS", "MET", "NH2", "PHE", "PRO", "PYL", "SEC", "SER", "THR", "TRP", "TYR", "VAL", };
static const char *oons_ACE_atom_name[] = {"CH3", };
static double oons_ACE_atom_radius[] = {2.00, };
static int oons_ACE_atom_class[] = {FREESASA_ATOM_APOLAR, };
static struct classifier_residue oons_ACE_cfg = {
    .name = "ACE", .n_atoms = 1,
    .atom_name = (char**) oons_ACE_atom_name,
    .atom_radius = (double*) oons_ACE_atom_radius,
    .atom_class = (freesasa_atom_class*) oons_ACE_atom_class,
    .max_area = {NULL, 0, 0, 0, 0, 0},
};

static const char *oons_ANY_atom_name[] = {"C5", "N", "O4", "C4", "C8", "OP1", "N1", "OP2", "C3'", "CM2", "P", "N9", "C6", "O2", "CA", "OXT", "O4'", "C5'", "C7", "O3'", "OP3", "O6", "N4", "N7", "C1'", "C", "C4'", "CB", "N2", "C2'", "O2'", "N3", "O", "O5'", "N6", "C2", };
static double oons_ANY_atom_radius[] = {1.75, 1.55, 1.40, 1.75, 1.75, 1.40, 1.55, 1.40, 1.75, 2.00, 1.80, 1.55, 1.75, 1.40, 2.00, 1.40, 1.40, 2.00, 1.75, 1.40, 1.40, 1.40, 1.55, 1.55, 1.75, 1.55, 1.75, 2.00, 1.55, 1.75, 1.40, 1.55, 1.40, 1.40, 1.55, 1.75, };
static int oons_ANY_atom_class[] = {FREESASA_ATOM_APOLAR, FREESASA_ATOM_POLAR, FREESASA_ATOM_POLAR, FREESASA_ATOM_APOLAR, FREESASA_ATOM_APOLAR, FREESASA_ATOM_POLAR, FREESASA_ATOM_POLAR, FREESASA_ATOM_POLAR, FREESASA_ATOM_APOLAR, FREESASA_ATOM_APOLAR, FREESASA_ATOM_POLAR, FREESASA_ATOM_POLAR, FREESASA_ATOM_APOLAR, FREESASA_ATOM_POLAR, FREESASA_ATOM_APOLAR, FREESASA_ATOM_POLAR, FREESASA_ATOM_POLAR, FREESASA_ATOM_APOLAR, FREESASA_ATOM_APOLAR, FREESASA_ATOM_POLAR, FREESASA_ATOM_POLAR, FREESASA_ATOM_POLAR, FREESASA_ATOM_POLAR, FREESASA_ATOM_POLAR, FREESASA_ATOM_APOLAR, FREESASA_ATOM_POLAR, FREESASA_ATOM_APOLAR, FREESASA_ATOM_APOLAR, FREESASA_ATOM_POLAR, FREESASA_ATOM_APOLAR, FREESASA_ATOM_POLAR, FREESASA_ATOM_POLAR, FREESASA_ATOM_POLAR, FREESASA_ATOM_POLAR, FREESASA_ATOM_POLAR, FREESASA_ATOM_APOLAR, };
static struct classifier_residue oons_ANY_cfg = {
    .name = "ANY", .n_atoms = 36,
    .atom_name = (char**) oons_ANY_atom_name,
    .atom_radius = (double*) oons_ANY_atom_radius,
    .atom_class = (freesasa_atom_class*) oons_ANY_atom_class,
    .max_area = {NULL, 0, 0, 0, 0, 0},
};

static const char *oons_ARG_atom_name[] = {"CG", "NH2", "NE", "CZ", "CD", "NH1", };
static double oons_ARG_atom_radius[] = {2.00, 1.55, 1.55, 2.00, 2.00, 1.55, };
static int oons_ARG_atom_class[] = {FREESASA_ATOM_APOLAR, FREESASA_ATOM_POLAR, FREESASA_ATOM_POLAR, FREESASA_ATOM_APOLAR, FREESASA_ATOM_APOLAR, FREESASA_ATOM_POLAR, };
static struct classifier_residue oons_ARG_cfg = {
    .name = "ARG", .n_atoms = 6,
    .atom_name = (char**) oons_ARG_atom_name,
    .atom_radius = (double*) oons_ARG_atom_radius,
    .atom_class = (freesasa_atom_class*) oons_ARG_atom_class,
    .max_area = {.name = "ARG", .total = 235.30, .main_chain = 38.31, .side_chain = 196.99, .polar = 125.27, .apolar = 110.03},
};

static const char *oons_ASN_atom_name[] = {"OD1", "CG", "ND2", };
static double oons_ASN_atom_radius[] = {1.40, 1.55, 1.55, };
static int oons_ASN_atom_class[] = {FREESASA_ATOM_POLAR, FREESASA_ATOM_POLAR, FREESASA_ATOM_POLAR, };
static struct classifier_residue oons_ASN_cfg = {
    .name = "ASN", .n_atoms = 3,
    .atom_name = (char**) oons_ASN_atom_name,
    .atom_radius = (double*) oons_ASN_atom_radius,
    .atom_class = (freesasa_atom_class*) oons_ASN_atom_class,
    .max_area = {.name = "ASN", .total = 143.47, .main_chain = 38.26, .side_chain = 105.21, .polar = 97.51, .apolar = 45.97},
};

static const char *oons_ASP_atom_name[] = {"OD2", "CG", "OD1", };
static double oons_ASP_atom_radius[] = {1.40, 1.55, 1.40, };
static int oons_ASP_atom_class[] = {FREESASA_ATOM_POLAR, FREESASA_ATOM_POLAR, FREESASA_ATOM_POLAR, };
static struct classifier_residue oons_ASP_cfg = {
    .name = "ASP", .n_atoms = 3,
    .atom_name = (char**) oons_ASP_atom_name,
    .atom_radius = (double*) oons_ASP_atom_radius,
    .atom_class = (freesasa_atom_class*) oons_ASP_atom_class,
    .max_area = {.name = "ASP", .total = 141.20, .main_chain = 38.87, .side_chain = 102.33, .polar = 95.17, .apolar = 46.03},
};

static const char *oons_ASX_atom_name[] = {"XD2", "CG", "XD1", "AD1", "AD2", };
static double oons_ASX_atom_radius[] = {1.5, 1.55, 1.5, 1.5, 1.5, };
static int oons_ASX_atom_class[] = {FREESASA_ATOM_POLAR, FREESASA_ATOM_POLAR, FREESASA_ATOM_POLAR, FREESASA_ATOM_POLAR, FREESASA_ATOM_POLAR, };
static struct classifier_residue oons_ASX_cfg = {
    .name = "ASX", .n_atoms = 5,
    .atom_name = (char**) oons_ASX_atom_name,
    .atom_radius = (double*) oons_ASX_atom_radius,
    .atom_class = (freesasa_atom_class*) oons_ASX_atom_class,
    .max_area = {NULL, 0, 0, 0, 0, 0},
};

static const char *oons_CSE_atom_name[] = {"SE", };
static double oons_CSE_atom_radius[] = {1.90, };
static int oons_CSE_atom_class[] = {FREESASA_ATOM_POLAR, };
static struct classifier_residue oons_CSE_cfg = {
    .name = "CSE", .n_atoms = 1,
    .atom_name = (char**) oons_CSE_atom_name,
    .atom_radius = (double*) oons_CSE_atom_radius,
    .atom_class = (freesasa_atom_class*) oons_CSE_atom_class,
    .max_area = {NULL, 0, 0, 0, 0, 0},
};

static const char *oons_CYS_atom_name[] = {"SG", };
static double oons_CYS_atom_radius[] = {2.00, };
static int oons_CYS_atom_class[] = {FREESASA_ATOM_POLAR, };
static struct classifier_residue oons_CYS_cfg = {
    .name = "CYS", .n_atoms = 1,
    .atom_name = (char**) oons_CYS_atom_name,
    .atom_radius = (double*) oons_CYS_atom_radius,
    .atom_class = (freesasa_atom_class*) oons_CYS_atom_class,
    .max_area = {.name = "CYS", .total = 140.29, .main_chain = 38.44, .side_chain = 101.85, .polar = 98.30, .apolar = 41.99},
};

static const char *oons_GLN_atom_name[] = {"NE2", "CG", "CD", "OE1", };
static double oons_GLN_atom_radius[] = {1.55, 2.00, 1.55, 1.40, };
static int oons_GLN_atom_class[] = {FREESASA_ATOM_POLAR, FREESASA_ATOM_APOLAR, FREESASA_ATOM_POLAR, FREESASA_ATOM_POLAR, };
static struct classifier_residue oons_GLN_cfg = {
    .name = "GLN", .n_atoms = 4,
    .atom_name = (char**) oons_GLN_atom_name,
    .atom_radius = (double*) oons_GLN_atom_radius,
    .atom_class = (freesasa_atom_class*) oons_GLN_atom_class,
    .max_area = {.name = "GLN", .total = 176.23, .main_chain = 38.31, .side_chain = 137.92, .polar = 122.17, .apolar = 54.06},
};

static const char *oons_GLU_atom_name[] = {"CG", "CD", "OE1", "OE2", };
static double oons_GLU_atom_radius[] = {2.00, 1.55, 1.40, 1.40, };
static int oons_GLU_atom_class[] = {FREESASA_ATOM_APOLAR, FREESASA_ATOM_POLAR, FREESASA_ATOM_POLAR, FREESASA_ATOM_POLAR, };
static struct classifier_residue oons_GLU_cfg = {
    .name = "GLU", .n_atoms = 4,
    .atom_name = (char**) oons_GLU_atom_name,
    .atom_radius = (double*) oons_GLU_atom_radius,
    .atom_class = (freesasa_atom_class*) oons_GLU_atom_class,
    .max_area = {.name = "GLU", .total = 172.43, .main_chain = 38.31, .side_chain = 134.11, .polar = 115.92, .apolar = 56.51},
};

static const char *oons_GLX_atom_name[] = {"XE2", "CD", "CG", "AE2", "XE1", "AE1", };
static double oons_GLX_atom_radius[] = {1.5, 1.55, 2.00, 1.5, 1.5, 1.5, };
static int oons_GLX_atom_class[] = {FREESASA_ATOM_POLAR, FREESASA_ATOM_POLAR, FREESASA_ATOM_APOLAR, FREESASA_ATOM_POLAR, FREESASA_ATOM_POLAR, FREESASA_ATOM_POLAR, };
static struct classifier_residue oons_GLX_cfg = {
    .name = "GLX", .n_atoms = 6,
    .atom_name = (char**) oons_GLX_atom_name,
    .atom_radius = (double*) oons_GLX_atom_radius,
    .atom_class = (freesasa_atom_class*) oons_GLX_atom_class,
    .max_area = {NULL, 0, 0, 0, 0, 0},
};

static const char *oons_HIS_atom_name[] = {"CD2", "ND1", "NE2", "CE1", "CG", };
static double oons_HIS_atom_radius[] = {1.75, 1.55, 1.55, 1.75, 1.75, };
static int oons_HIS_atom_class[] = {FREESASA_ATOM_APOLAR, FREESASA_ATOM_POLAR, FREESASA_ATOM_POLAR, FREESASA_ATOM_APOLAR, FREESASA_ATOM_APOLAR, };
static struct classifier_residue oons_HIS_cfg = {
    .name = "HIS", .n_atoms = 5,
    .atom_name = (char**) oons_HIS_atom_name,
    .atom_radius = (double*) oons_HIS_atom_radius,
    .atom_class = (freesasa_atom_class*) oons_HIS_atom_class,
    .max_area = {.name = "HIS", .total = 180.78, .main_chain = 36.04, .side_chain = 144.74, .polar = 73.26, .apolar = 107.52},
};

static const char *oons_HOH_atom_name[] = {"O", };
static double oons_HOH_atom_radius[] = {1.40, };
static int oons_HOH_atom_class[] = {FREESASA_ATOM_POLAR, };
static struct classifier_residue oons_HOH_cfg = {
    .name = "HOH", .n_atoms = 1,
    .atom_name = (char**) oons_HOH_atom_name,
    .atom_radius = (double*) oons_HOH_atom_radius,
    .atom_class = (freesasa_atom_class*) oons_HOH_atom_class,
    .max_area = {NULL, 0, 0, 0, 0, 0},
};

static const char *oons_ILE_atom_name[] = {"CD1", "CG2", "CG1", };
static double oons_ILE_atom_radius[] = {2.00, 2.00, 2.00, };
static int oons_ILE_atom_class[] = {FREESASA_ATOM_APOLAR, FREESASA_ATOM_APOLAR, FREESASA_ATOM_APOLAR, };
static struct classifier_residue oons_ILE_cfg = {
    .name = "ILE", .n_atoms = 3,
    .atom_name = (char**) oons_ILE_atom_name,
    .atom_radius = (double*) oons_ILE_atom_radius,
    .atom_class = (freesasa_atom_class*) oons_ILE_atom_class,
    .max_area = {.name = "ILE", .total = 182.12, .main_chain = 37.96, .side_chain = 144.16, .polar = 31.67, .apolar = 150.45},
};

static const char *oons_LEU_atom_name[] = {"CG", "CD1", "CD2", };
static double oons_LEU_atom_radius[] = {2.00, 2.00, 2.00, };
static int oons_LEU_atom_class[] = {FREESASA_ATOM_APOLAR, FREESASA_ATOM_APOLAR, FREESASA_ATOM_APOLAR, };
static struct classifier_residue oons_LEU_cfg = {
    .name = "LEU", .n_atoms = 3,
    .atom_name = (char**) oons_LEU_atom_name,
    .atom_radius = (double*) oons_LEU_atom_radius,
    .atom_class = (freesasa_atom_class*) oons_LEU_atom_class,
    .max_area = {.name = "LEU", .total = 185.43, .main_chain = 35.34, .side_chain = 150.08, .polar = 31.73, .apolar = 153.69},
};

static const char *oons_LYS_atom_name[] = {"CD", "CE", "CG", "NZ", };
static double oons_LYS_atom_radius[] = {2.00, 2.00, 2.00, 1.55, };
static int oons_LYS_atom_class[] = {FREESASA_ATOM_APOLAR, FREESASA_ATOM_APOLAR, FREESASA_ATOM_APOLAR, FREESASA_ATOM_POLAR, };
static struct classifier_residue oons_LYS_cfg = {
    .name = "LYS", .n_atoms = 4,
    .atom_name = (char**) oons_LYS_atom_name,
    .atom_radius = (double*) oons_LYS_atom_radius,
    .atom_class = (freesasa_atom_class*) oons_LYS_atom_class,
    .max_area = {.name = "LYS", .total = 205.80, .main_chain = 38.31, .side_chain = 167.49, .polar = 78.02, .apolar = 127.78},
};

static const char *oons_MET_atom_name[] = {"SD", "CG", "CE", };
static double oons_MET_atom_radius[] = {2.00, 2.00, 2.00, };
static int oons_MET_atom_class[] = {FREESASA_ATOM_POLAR, FREESASA_ATOM_APOLAR, FREESASA_ATOM_APOLAR, };
static struct classifier_residue oons_MET_cfg = {
    .name = "MET", .n_atoms = 3,
    .atom_name = (char**) oons_MET_atom_name,
    .atom_radius = (double*) oons_MET_atom_radius,
    .atom_class = (freesasa_atom_class*) oons_MET_atom_class,
    .max_area = {.name = "MET", .total = 201.66, .main_chain = 38.31, .side_chain = 163.35, .polar = 78.68, .apolar = 122.98},
};

static const char *oons_NH2_atom_name[] = {"NH2", };
static double oons_NH2_atom_radius[] = {1.55, };
static int oons_NH2_atom_class[] = {FREESASA_ATOM_POLAR, };
static struct classifier_residue oons_NH2_cfg = {
    .name = "NH2", .n_atoms = 1,
    .atom_name = (char**) oons_NH2_atom_name,
    .atom_radius = (double*) oons_NH2_atom_radius,
    .atom_class = (freesasa_atom_class*) oons_NH2_atom_class,
    .max_area = {NULL, 0, 0, 0, 0, 0},
};

static const char *oons_PHE_atom_name[] = {"CD2", "CE2", "CG", "CE1", "CD1", "CZ", };
static double oons_PHE_atom_radius[] = {1.75, 1.75, 1.75, 1.75, 1.75, 1.75, };
static int oons_PHE_atom_class[] = {FREESASA_ATOM_APOLAR, FREESASA_ATOM_APOLAR, FREESASA_ATOM_APOLAR, FREESASA_ATOM_APOLAR, FREESASA_ATOM_APOLAR, FREESASA_ATOM_APOLAR, };
static struct classifier_residue oons_PHE_cfg = {
    .name = "PHE", .n_atoms = 6,
    .atom_name = (char**) oons_PHE_atom_name,
    .atom_radius = (double*) oons_PHE_atom_radius,
    .atom_class = (freesasa_atom_class*) oons_PHE_atom_class,
    .max_area = {.name = "PHE", .total = 199.28, .main_chain = 35.20, .side_chain = 164.08, .polar = 30.08, .apolar = 169.20},
};

static const char *oons_PRO_atom_name[] = {"CB", "CD", "CG", };
static double oons_PRO_atom_radius[] = {1.75, 1.75, 1.75, };
static int oons_PRO_atom_class[] = {FREESASA_ATOM_APOLAR, FREESASA_ATOM_APOLAR, FREESASA_ATOM_APOLAR, };
static struct classifier_residue oons_PRO_cfg = {
    .name = "PRO", .n_atoms = 3,
    .atom_name = (char**) oons_PRO_atom_name,
    .atom_radius = (double*) oons_PRO_atom_radius,
    .atom_class = (freesasa_atom_class*) oons_PRO_atom_class,
    .max_area = {.name = "PRO", .total = 128.18, .main_chain = 31.08, .side_chain = 97.10, .polar = 13.95, .apolar = 114.23},
};

static const char *oons_PYL_atom_name[] = {"C2", "O2", "N2", "CA2", "CD2", "CD", "CE", "CG", "CE2", "NZ", "CG2", "CB2", };
static double oons_PYL_atom_radius[] = {1.55, 1.40, 1.55, 1.75, 1.75, 2.00, 2.00, 2.00, 1.75, 1.55, 1.75, 2.00, };
static int oons_PYL_atom_class[] = {FREESASA_ATOM_POLAR, FREESASA_ATOM_POLAR, FREESASA_ATOM_POLAR, FREESASA_ATOM_APOLAR, FREESASA_ATOM_APOLAR, FREESASA_ATOM_APOLAR, FREESASA_ATOM_APOLAR, FREESASA_ATOM_APOLAR, FREESASA_ATOM_APOLAR, FREESASA_ATOM_POLAR, FREESASA_ATOM_APOLAR, FREESASA_ATOM_APOLAR, };
static struct classifier_residue oons_PYL_cfg = {
    .name = "PYL", .n_atoms = 12,
    .atom_name = (char**) oons_PYL_atom_name,
    .atom_radius = (double*) oons_PYL_atom_radius,
    .atom_class = (freesasa_atom_class*) oons_PYL_atom_class,
    .max_area = {NULL, 0, 0, 0, 0, 0},
};

static const char *oons_SEC_atom_name[] = {"SE", };
static double oons_SEC_atom_radius[] = {1.90, };
static int oons_SEC_atom_class[] = {FREESASA_ATOM_POLAR, };
static struct classifier_residue oons_SEC_cfg = {
    .name = "SEC", .n_atoms = 1,
    .atom_name = (char**) oons_SEC_atom_name,
    .atom_radius = (double*) oons_SEC_atom_radius,
    .atom_class = (freesasa_atom_class*) oons_SEC_atom_class,
    .max_area = {NULL, 0, 0, 0, 0, 0},
};

static const char *oons_SER_atom_name[] = {"OG", };
static double oons_SER_atom_radius[] = {1.40, };
static int oons_SER_atom_class[] = {FREESASA_ATOM_POLAR, };
static struct classifier_residue oons_SER_cfg = {
    .name = "SER", .n_atoms = 1,
    .atom_name = (char**) oons_SER_atom_name,
    .atom_radius = (double*) oons_SER_atom_radius,
    .atom_class = (freesasa_atom_class*) oons_SER_atom_class,
    .max_area = {.name = "SER", .total = 118.43, .main_chain = 40.20, .side_chain = 78.23, .polar = 60.41, .apolar = 58.02},
};

static const char *oons_THR_atom_name[] = {"OG1", "CG2", };
static double oons_THR_atom_radius[] = {1.40, 2.00, };
static int oons_THR_atom_class[] = {FREESASA_ATOM_POLAR, FREESASA_ATOM_APOLAR, };
static struct classifier_residue oons_THR_cfg = {
    .name = "THR", .n_atoms = 2,
    .atom_name = (char**) oons_THR_atom_name,
    .atom_radius = (double*) oons_THR_atom_radius,
    .atom_class = (freesasa_atom_class*) oons_THR_atom_class,
    .max_area = {.name = "THR", .total = 142.41, .main_chain = 38.32, .side_chain = 104.08, .polar = 56.42, .apolar = 85.99},
};

static const char *oons_TRP_atom_name[] = {"CD2", "CZ2", "NE1", "CD1", "CG", "CE2", "CH2", "CE3", "CZ3", };
static double oons_TRP_atom_radius[] = {1.75, 1.75, 1.55, 1.75, 1.75, 1.75, 1.75, 1.75, 1.75, };
static int oons_TRP_atom_class[] = {FREESASA_ATOM_APOLAR, FREESASA_ATOM_APOLAR, FREESASA_ATOM_POLAR, FREESASA_ATOM_APOLAR, FREESASA_ATOM_APOLAR, FREESASA_ATOM_APOLAR, FREESASA_ATOM_APOLAR, FREESASA_ATOM_APOLAR, FREESASA_ATOM_APOLAR, };
static struct classifier_residue oons_TRP_cfg = {
    .name = "TRP", .n_atoms = 9,
    .atom_name = (char**) oons_TRP_atom_name,
    .atom_radius = (double*) oons_TRP_atom_radius,
    .atom_class = (freesasa_atom_class*) oons_TRP_atom_class,
    .max_area = {.name = "TRP", .total = 247.08, .main_chain = 39.43, .side_chain = 207.65, .polar = 52.90, .apolar = 194.18},
};

static const char *oons_TYR_atom_name[] = {"CZ", "CG", "CE1", "CD1", "CE2", "CD2", "OH", };
static double oons_TYR_atom_radius[] = {1.75, 1.75, 1.75, 1.75, 1.75, 1.75, 1.40, };
static int oons_TYR_atom_class[] = {FREESASA_ATOM_APOLAR, FREESASA_ATOM_APOLAR, FREESASA_ATOM_APOLAR, FREESASA_ATOM_APOLAR, FREESASA_ATOM_APOLAR, FREESASA_ATOM_APOLAR, FREESASA_ATOM_POLAR, };
static struct classifier_residue oons_TYR_cfg = {
    .name = "TYR", .n_atoms = 7,
    .atom_name = (char**) oons_TYR_atom_name,
    .atom_radius = (double*) oons_TYR_atom_radius,
    .atom_class = (freesasa_atom_class*) oons_TYR_atom_class,
    .max_area = {.name = "TYR", .total = 212.31, .main_chain = 35.20, .side_chain = 177.11, .polar = 72.41, .apolar = 139.90},
};

static const char *oons_VAL_atom_name[] = {"CG2", "CG1", };
static double oons_VAL_atom_radius[] = {2.00, 2.00, };
static int oons_VAL_atom_class[] = {FREESASA_ATOM_APOLAR, FREESASA_ATOM_APOLAR, };
static struct classifier_residue oons_VAL_cfg = {
    .name = "VAL", .n_atoms = 2,
    .atom_name = (char**) oons_VAL_atom_name,
    .atom_radius = (double*) oons_VAL_atom_radius,
    .atom_class = (freesasa_atom_class*) oons_VAL_atom_class,
    .max_area = {.name = "VAL", .total = 157.64, .main_chain = 37.96, .side_chain = 119.68, .polar = 31.70, .apolar = 125.94},
};

static struct classifier_residue *oons_residue_cfg[] = {
    &oons_ACE_cfg, &oons_ANY_cfg, &oons_ARG_cfg, &oons_ASN_cfg, &oons_ASP_cfg, &oons_ASX_cfg, &oons_CSE_cfg, &oons_CYS_cfg, &oons_GLN_cfg, &oons_GLU_cfg, &oons_GLX_cfg, &oons_HIS_cfg, &oons_HOH_cfg, &oons_ILE_cfg, &oons_LEU_cfg, &oons_LYS_cfg, &oons_MET_cfg, &oons_NH2_cfg, &oons_PHE_cfg, &oons_PRO_cfg, &oons_PYL_cfg, &oons_SEC_cfg, &oons_SER_cfg, &oons_THR_cfg, &oons_TRP_cfg, &oons_TYR_cfg, &oons_VAL_cfg, };

const freesasa_classifier freesasa_oons_classifier = {
    .n_residues = 27,    .residue_name = (char**) oons_residue_name,
    .residue = (struct classifier_residue **) oons_residue_cfg,
    .name = "OONS",
};

