#include "classifier.h"

/* 
   The classification in rsa.c depends on apolar atoms having class 0,
   and polar non-zero in freesasa_default_classifier. Optimally there
   would be a way to make this foolproof without resorting to string
   comparison. (In this context we accept lumping together water and
   polar).

   If you overwrite this file make sure this is taken into
   consideration, so that RSA is not broken, until there is a cleaner
   solution in place.
*/


/* Autogenerated code from the script config2c.pl */

static const char *residue_name[] = {"ACE", "T", "PRO", "ILE", "ASX", "CYS", "GLY", "DC", "NH2", "GLN", "SER", "DI", "ASN", "VAL", "TYR", "GLU", "ALA", "MET", "I", "HIS", "G", "PYL", "GLX", "DU", "U", "ASP", "SEC", "LYS", "HOH", "TRP", "DG", "PHE", "C", "DT", "A", "LEU", "ARG", "THR", "DA", };
static const char *class_name[] = {"Apolar", "Polar", "Water", };

static const char *ACE_atom_name[] = {"O", "CH3", "C", };
static double ACE_atom_radius[] = {1.42, 1.88, 1.76, };
static int ACE_atom_class[] = {1, 0, 0, };
static struct classifier_residue ACE_cfg = {
    .name = "ACE", .n_atoms = 3,
    .atom_name = (char**)ACE_atom_name,
    .atom_radius = (double*)ACE_atom_radius,
    .atom_class = (int*)ACE_atom_class };

static const char *T_atom_name[] = {"N3", "OP1", "C3'", "C2", "C6", "N1", "C5", "C1'", "O2", "P", "C7", "O4'", "O3'", "C4", "C5'", "OP2", "C2'", "C4'", "O5'", "OP3", "O4", };
static double T_atom_radius[] = {1.64, 1.42, 1.88, 1.61, 1.76, 1.64, 1.61, 1.88, 1.42, 1.8, 1.88, 1.46, 1.46, 1.61, 1.88, 1.46, 1.88, 1.88, 1.46, 1.46, 1.42, };
static int T_atom_class[] = {1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, };
static struct classifier_residue T_cfg = {
    .name = "T", .n_atoms = 21,
    .atom_name = (char**)T_atom_name,
    .atom_radius = (double*)T_atom_radius,
    .atom_class = (int*)T_atom_class };

static const char *PRO_atom_name[] = {"O", "N", "CB", "CD", "C", "CG", "CA", "OXT", };
static double PRO_atom_radius[] = {1.42, 1.64, 1.88, 1.88, 1.61, 1.88, 1.88, 1.46, };
static int PRO_atom_class[] = {1, 1, 0, 0, 0, 0, 0, 1, };
static struct classifier_residue PRO_cfg = {
    .name = "PRO", .n_atoms = 8,
    .atom_name = (char**)PRO_atom_name,
    .atom_radius = (double*)PRO_atom_radius,
    .atom_class = (int*)PRO_atom_class };

static const char *ILE_atom_name[] = {"O", "N", "CB", "CG2", "CD1", "C", "CG1", "CA", "OXT", };
static double ILE_atom_radius[] = {1.42, 1.64, 1.88, 1.88, 1.88, 1.61, 1.88, 1.88, 1.46, };
static int ILE_atom_class[] = {1, 1, 0, 0, 0, 0, 0, 0, 1, };
static struct classifier_residue ILE_cfg = {
    .name = "ILE", .n_atoms = 9,
    .atom_name = (char**)ILE_atom_name,
    .atom_radius = (double*)ILE_atom_radius,
    .atom_class = (int*)ILE_atom_class };

static const char *ASX_atom_name[] = {"XD2", "O", "N", "CB", "XD1", "C", "CG", "CA", "OXT", };
static double ASX_atom_radius[] = {1.5, 1.42, 1.64, 1.88, 1.5, 1.61, 1.61, 1.88, 1.46, };
static int ASX_atom_class[] = {1, 1, 1, 0, 1, 0, 0, 0, 1, };
static struct classifier_residue ASX_cfg = {
    .name = "ASX", .n_atoms = 9,
    .atom_name = (char**)ASX_atom_name,
    .atom_radius = (double*)ASX_atom_radius,
    .atom_class = (int*)ASX_atom_class };

static const char *CYS_atom_name[] = {"O", "C", "N", "CB", "CA", "OXT", "SG", };
static double CYS_atom_radius[] = {1.42, 1.61, 1.64, 1.88, 1.88, 1.46, 1.77, };
static int CYS_atom_class[] = {1, 0, 1, 0, 0, 1, 1, };
static struct classifier_residue CYS_cfg = {
    .name = "CYS", .n_atoms = 7,
    .atom_name = (char**)CYS_atom_name,
    .atom_radius = (double*)CYS_atom_radius,
    .atom_class = (int*)CYS_atom_class };

static const char *GLY_atom_name[] = {"O", "C", "N", "CA", "OXT", };
static double GLY_atom_radius[] = {1.42, 1.61, 1.64, 1.88, 1.46, };
static int GLY_atom_class[] = {1, 0, 1, 0, 1, };
static struct classifier_residue GLY_cfg = {
    .name = "GLY", .n_atoms = 5,
    .atom_name = (char**)GLY_atom_name,
    .atom_radius = (double*)GLY_atom_radius,
    .atom_class = (int*)GLY_atom_class };

static const char *DC_atom_name[] = {"N3", "OP1", "C3'", "C2", "C6", "N1", "C5", "C1'", "O2", "P", "O4'", "O3'", "C4", "C5'", "OP2", "C2'", "C4'", "O5'", "OP3", "N4", };
static double DC_atom_radius[] = {1.64, 1.42, 1.88, 1.61, 1.76, 1.64, 1.76, 1.88, 1.42, 1.8, 1.46, 1.46, 1.61, 1.88, 1.46, 1.88, 1.88, 1.46, 1.46, 1.64, };
static int DC_atom_class[] = {1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, };
static struct classifier_residue DC_cfg = {
    .name = "DC", .n_atoms = 20,
    .atom_name = (char**)DC_atom_name,
    .atom_radius = (double*)DC_atom_radius,
    .atom_class = (int*)DC_atom_class };

static const char *NH2_atom_name[] = {"N", };
static double NH2_atom_radius[] = {1.64, };
static int NH2_atom_class[] = {1, };
static struct classifier_residue NH2_cfg = {
    .name = "NH2", .n_atoms = 1,
    .atom_name = (char**)NH2_atom_name,
    .atom_radius = (double*)NH2_atom_radius,
    .atom_class = (int*)NH2_atom_class };

static const char *GLN_atom_name[] = {"O", "NE2", "N", "OE1", "CB", "CD", "C", "CG", "CA", "OXT", };
static double GLN_atom_radius[] = {1.42, 1.64, 1.64, 1.42, 1.88, 1.61, 1.61, 1.88, 1.88, 1.46, };
static int GLN_atom_class[] = {1, 1, 1, 1, 0, 0, 0, 0, 0, 1, };
static struct classifier_residue GLN_cfg = {
    .name = "GLN", .n_atoms = 10,
    .atom_name = (char**)GLN_atom_name,
    .atom_radius = (double*)GLN_atom_radius,
    .atom_class = (int*)GLN_atom_class };

static const char *SER_atom_name[] = {"O", "OG", "C", "N", "CB", "CA", "OXT", };
static double SER_atom_radius[] = {1.42, 1.46, 1.61, 1.64, 1.88, 1.88, 1.46, };
static int SER_atom_class[] = {1, 1, 0, 1, 0, 0, 1, };
static struct classifier_residue SER_cfg = {
    .name = "SER", .n_atoms = 7,
    .atom_name = (char**)SER_atom_name,
    .atom_radius = (double*)SER_atom_radius,
    .atom_class = (int*)SER_atom_class };

static const char *DI_atom_name[] = {"N9", "N3", "OP1", "C3'", "C8", "C2", "N1", "C6", "C5", "C1'", "P", "N7", "O4'", "O3'", "C4", "C5'", "OP2", "C2'", "C4'", "O5'", "OP3", "O6", };
static double DI_atom_radius[] = {1.64, 1.64, 1.42, 1.88, 1.76, 1.76, 1.64, 1.61, 1.61, 1.88, 1.8, 1.64, 1.46, 1.46, 1.61, 1.88, 1.46, 1.88, 1.88, 1.46, 1.46, 1.42, };
static int DI_atom_class[] = {1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, };
static struct classifier_residue DI_cfg = {
    .name = "DI", .n_atoms = 22,
    .atom_name = (char**)DI_atom_name,
    .atom_radius = (double*)DI_atom_radius,
    .atom_class = (int*)DI_atom_class };

static const char *ASN_atom_name[] = {"O", "N", "CB", "ND2", "C", "OD1", "CG", "CA", "OXT", };
static double ASN_atom_radius[] = {1.42, 1.64, 1.88, 1.64, 1.61, 1.42, 1.61, 1.88, 1.46, };
static int ASN_atom_class[] = {1, 1, 0, 1, 0, 1, 0, 0, 1, };
static struct classifier_residue ASN_cfg = {
    .name = "ASN", .n_atoms = 9,
    .atom_name = (char**)ASN_atom_name,
    .atom_radius = (double*)ASN_atom_radius,
    .atom_class = (int*)ASN_atom_class };

static const char *VAL_atom_name[] = {"O", "N", "CB", "CG2", "C", "CG1", "CA", "OXT", };
static double VAL_atom_radius[] = {1.42, 1.64, 1.88, 1.88, 1.61, 1.88, 1.88, 1.46, };
static int VAL_atom_class[] = {1, 1, 0, 0, 0, 0, 0, 1, };
static struct classifier_residue VAL_cfg = {
    .name = "VAL", .n_atoms = 8,
    .atom_name = (char**)VAL_atom_name,
    .atom_radius = (double*)VAL_atom_radius,
    .atom_class = (int*)VAL_atom_class };

static const char *TYR_atom_name[] = {"O", "N", "CB", "CE2", "CD1", "CD2", "CZ", "CE1", "C", "CG", "OH", "CA", "OXT", };
static double TYR_atom_radius[] = {1.42, 1.64, 1.88, 1.76, 1.76, 1.76, 1.61, 1.76, 1.61, 1.61, 1.46, 1.88, 1.46, };
static int TYR_atom_class[] = {1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, };
static struct classifier_residue TYR_cfg = {
    .name = "TYR", .n_atoms = 13,
    .atom_name = (char**)TYR_atom_name,
    .atom_radius = (double*)TYR_atom_radius,
    .atom_class = (int*)TYR_atom_class };

static const char *GLU_atom_name[] = {"O", "N", "OE1", "CB", "OE2", "CD", "C", "CG", "CA", "OXT", };
static double GLU_atom_radius[] = {1.42, 1.64, 1.42, 1.88, 1.46, 1.61, 1.61, 1.88, 1.88, 1.46, };
static int GLU_atom_class[] = {1, 1, 1, 0, 1, 0, 0, 0, 0, 1, };
static struct classifier_residue GLU_cfg = {
    .name = "GLU", .n_atoms = 10,
    .atom_name = (char**)GLU_atom_name,
    .atom_radius = (double*)GLU_atom_radius,
    .atom_class = (int*)GLU_atom_class };

static const char *ALA_atom_name[] = {"O", "C", "N", "CB", "CA", "OXT", };
static double ALA_atom_radius[] = {1.42, 1.61, 1.64, 1.88, 1.88, 1.46, };
static int ALA_atom_class[] = {1, 0, 1, 0, 0, 1, };
static struct classifier_residue ALA_cfg = {
    .name = "ALA", .n_atoms = 6,
    .atom_name = (char**)ALA_atom_name,
    .atom_radius = (double*)ALA_atom_radius,
    .atom_class = (int*)ALA_atom_class };

static const char *MET_atom_name[] = {"O", "N", "CB", "CE", "C", "CG", "SD", "CA", "OXT", };
static double MET_atom_radius[] = {1.42, 1.64, 1.88, 1.88, 1.61, 1.88, 1.77, 1.88, 1.46, };
static int MET_atom_class[] = {1, 1, 0, 0, 0, 0, 1, 0, 1, };
static struct classifier_residue MET_cfg = {
    .name = "MET", .n_atoms = 9,
    .atom_name = (char**)MET_atom_name,
    .atom_radius = (double*)MET_atom_radius,
    .atom_class = (int*)MET_atom_class };

static const char *I_atom_name[] = {"N9", "N3", "OP1", "C3'", "C8", "C2", "N1", "C6", "C5", "C1'", "P", "N7", "O4'", "O3'", "C4", "C5'", "OP2", "C2'", "C4'", "O5'", "OP3", "O2'", "O6", };
static double I_atom_radius[] = {1.64, 1.64, 1.42, 1.88, 1.76, 1.76, 1.64, 1.61, 1.61, 1.88, 1.8, 1.64, 1.46, 1.46, 1.61, 1.88, 1.46, 1.88, 1.88, 1.46, 1.46, 1.46, 1.42, };
static int I_atom_class[] = {1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, };
static struct classifier_residue I_cfg = {
    .name = "I", .n_atoms = 23,
    .atom_name = (char**)I_atom_name,
    .atom_radius = (double*)I_atom_radius,
    .atom_class = (int*)I_atom_class };

static const char *HIS_atom_name[] = {"O", "NE2", "N", "CB", "ND1", "CD2", "CE1", "C", "CG", "CA", "OXT", };
static double HIS_atom_radius[] = {1.42, 1.64, 1.64, 1.88, 1.64, 1.76, 1.76, 1.61, 1.61, 1.88, 1.46, };
static int HIS_atom_class[] = {1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, };
static struct classifier_residue HIS_cfg = {
    .name = "HIS", .n_atoms = 11,
    .atom_name = (char**)HIS_atom_name,
    .atom_radius = (double*)HIS_atom_radius,
    .atom_class = (int*)HIS_atom_class };

static const char *G_atom_name[] = {"N9", "N3", "OP1", "N2", "C3'", "C8", "C2", "N1", "C6", "C5", "C1'", "P", "N7", "O4'", "O3'", "C4", "C5'", "OP2", "C2'", "C4'", "O5'", "OP3", "O2'", "O6", };
static double G_atom_radius[] = {1.64, 1.64, 1.42, 1.64, 1.88, 1.76, 1.61, 1.64, 1.61, 1.61, 1.88, 1.8, 1.64, 1.46, 1.46, 1.61, 1.88, 1.46, 1.88, 1.88, 1.46, 1.46, 1.46, 1.42, };
static int G_atom_class[] = {1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, };
static struct classifier_residue G_cfg = {
    .name = "G", .n_atoms = 24,
    .atom_name = (char**)G_atom_name,
    .atom_radius = (double*)G_atom_radius,
    .atom_class = (int*)G_atom_class };

static const char *PYL_atom_name[] = {"CA2", "N", "CB", "N2", "CG2", "CD2", "CD", "C", "CG", "CA", "C2", "O", "O2", "CB2", "CE", "CE2", "NZ", "OXT", };
static double PYL_atom_radius[] = {1.88, 1.64, 1.88, 1.64, 1.88, 1.88, 1.88, 1.61, 1.88, 1.88, 1.61, 1.42, 1.42, 1.88, 1.88, 1.76, 1.64, 1.46, };
static int PYL_atom_class[] = {0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, };
static struct classifier_residue PYL_cfg = {
    .name = "PYL", .n_atoms = 18,
    .atom_name = (char**)PYL_atom_name,
    .atom_radius = (double*)PYL_atom_radius,
    .atom_class = (int*)PYL_atom_class };

static const char *GLX_atom_name[] = {"O", "N", "XE2", "CB", "CD", "C", "CG", "CA", "XE1", "OXT", };
static double GLX_atom_radius[] = {1.42, 1.64, 1.5, 1.88, 1.61, 1.61, 1.88, 1.88, 1.5, 1.46, };
static int GLX_atom_class[] = {1, 1, 1, 0, 0, 0, 0, 0, 1, 1, };
static struct classifier_residue GLX_cfg = {
    .name = "GLX", .n_atoms = 10,
    .atom_name = (char**)GLX_atom_name,
    .atom_radius = (double*)GLX_atom_radius,
    .atom_class = (int*)GLX_atom_class };

static const char *DU_atom_name[] = {"N3", "OP1", "C3'", "C2", "C6", "N1", "C5", "C1'", "O2", "P", "O4'", "O3'", "C4", "C5'", "OP2", "C2'", "C4'", "O5'", "OP3", "O4", };
static double DU_atom_radius[] = {1.64, 1.42, 1.88, 1.61, 1.76, 1.64, 1.76, 1.88, 1.42, 1.8, 1.46, 1.46, 1.61, 1.88, 1.46, 1.88, 1.88, 1.46, 1.46, 1.42, };
static int DU_atom_class[] = {1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, };
static struct classifier_residue DU_cfg = {
    .name = "DU", .n_atoms = 20,
    .atom_name = (char**)DU_atom_name,
    .atom_radius = (double*)DU_atom_radius,
    .atom_class = (int*)DU_atom_class };

static const char *U_atom_name[] = {"N3", "OP1", "C3'", "C2", "C6", "N1", "C5", "C1'", "O2", "P", "O4'", "O3'", "C4", "C5'", "OP2", "C2'", "C4'", "O5'", "OP3", "O2'", "O4", };
static double U_atom_radius[] = {1.64, 1.42, 1.88, 1.61, 1.76, 1.64, 1.76, 1.88, 1.42, 1.8, 1.46, 1.46, 1.61, 1.88, 1.46, 1.88, 1.88, 1.46, 1.46, 1.46, 1.42, };
static int U_atom_class[] = {1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, };
static struct classifier_residue U_cfg = {
    .name = "U", .n_atoms = 21,
    .atom_name = (char**)U_atom_name,
    .atom_radius = (double*)U_atom_radius,
    .atom_class = (int*)U_atom_class };

static const char *ASP_atom_name[] = {"O", "N", "CB", "OD2", "C", "OD1", "CG", "CA", "OXT", };
static double ASP_atom_radius[] = {1.42, 1.64, 1.88, 1.46, 1.61, 1.42, 1.61, 1.88, 1.46, };
static int ASP_atom_class[] = {1, 1, 0, 1, 0, 1, 0, 0, 1, };
static struct classifier_residue ASP_cfg = {
    .name = "ASP", .n_atoms = 9,
    .atom_name = (char**)ASP_atom_name,
    .atom_radius = (double*)ASP_atom_radius,
    .atom_class = (int*)ASP_atom_class };

static const char *SEC_atom_name[] = {"SE", "O", "C", "N", "CB", "CA", "OXT", };
static double SEC_atom_radius[] = {1.9, 1.42, 1.61, 1.64, 1.88, 1.88, 1.46, };
static int SEC_atom_class[] = {1, 1, 0, 1, 0, 0, 1, };
static struct classifier_residue SEC_cfg = {
    .name = "SEC", .n_atoms = 7,
    .atom_name = (char**)SEC_atom_name,
    .atom_radius = (double*)SEC_atom_radius,
    .atom_class = (int*)SEC_atom_class };

static const char *LYS_atom_name[] = {"O", "N", "CB", "CE", "CD", "C", "CG", "NZ", "CA", "OXT", };
static double LYS_atom_radius[] = {1.42, 1.64, 1.88, 1.88, 1.88, 1.61, 1.88, 1.64, 1.88, 1.46, };
static int LYS_atom_class[] = {1, 1, 0, 0, 0, 0, 0, 1, 0, 1, };
static struct classifier_residue LYS_cfg = {
    .name = "LYS", .n_atoms = 10,
    .atom_name = (char**)LYS_atom_name,
    .atom_radius = (double*)LYS_atom_radius,
    .atom_class = (int*)LYS_atom_class };

static const char *HOH_atom_name[] = {"O", };
static double HOH_atom_radius[] = {1.46, };
static int HOH_atom_class[] = {2, };
static struct classifier_residue HOH_cfg = {
    .name = "HOH", .n_atoms = 1,
    .atom_name = (char**)HOH_atom_name,
    .atom_radius = (double*)HOH_atom_radius,
    .atom_class = (int*)HOH_atom_class };

static const char *TRP_atom_name[] = {"O", "CZ2", "N", "CB", "CE2", "NE1", "CD1", "CD2", "CH2", "C", "CE3", "CG", "CZ3", "CA", "OXT", };
static double TRP_atom_radius[] = {1.42, 1.76, 1.64, 1.88, 1.61, 1.64, 1.76, 1.61, 1.76, 1.61, 1.76, 1.61, 1.76, 1.88, 1.46, };
static int TRP_atom_class[] = {1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, };
static struct classifier_residue TRP_cfg = {
    .name = "TRP", .n_atoms = 15,
    .atom_name = (char**)TRP_atom_name,
    .atom_radius = (double*)TRP_atom_radius,
    .atom_class = (int*)TRP_atom_class };

static const char *DG_atom_name[] = {"N9", "N3", "OP1", "N2", "C3'", "C8", "C2", "N1", "C6", "C5", "C1'", "P", "N7", "O4'", "O3'", "C4", "C5'", "OP2", "C2'", "C4'", "O5'", "OP3", "O6", };
static double DG_atom_radius[] = {1.64, 1.64, 1.42, 1.64, 1.88, 1.76, 1.61, 1.64, 1.61, 1.61, 1.88, 1.8, 1.64, 1.46, 1.46, 1.61, 1.88, 1.46, 1.88, 1.88, 1.46, 1.46, 1.42, };
static int DG_atom_class[] = {1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, };
static struct classifier_residue DG_cfg = {
    .name = "DG", .n_atoms = 23,
    .atom_name = (char**)DG_atom_name,
    .atom_radius = (double*)DG_atom_radius,
    .atom_class = (int*)DG_atom_class };

static const char *PHE_atom_name[] = {"O", "N", "CB", "CE2", "CD1", "CD2", "CZ", "CE1", "C", "CG", "CA", "OXT", };
static double PHE_atom_radius[] = {1.42, 1.64, 1.88, 1.76, 1.76, 1.76, 1.76, 1.76, 1.61, 1.61, 1.88, 1.46, };
static int PHE_atom_class[] = {1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, };
static struct classifier_residue PHE_cfg = {
    .name = "PHE", .n_atoms = 12,
    .atom_name = (char**)PHE_atom_name,
    .atom_radius = (double*)PHE_atom_radius,
    .atom_class = (int*)PHE_atom_class };

static const char *C_atom_name[] = {"N3", "OP1", "C3'", "C2", "C6", "N1", "C5", "C1'", "O2", "P", "O4'", "O3'", "C4", "C5'", "OP2", "C2'", "C4'", "O5'", "OP3", "O2'", "N4", };
static double C_atom_radius[] = {1.64, 1.42, 1.88, 1.61, 1.76, 1.64, 1.76, 1.88, 1.42, 1.8, 1.46, 1.46, 1.61, 1.88, 1.46, 1.88, 1.88, 1.46, 1.46, 1.46, 1.64, };
static int C_atom_class[] = {1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, };
static struct classifier_residue C_cfg = {
    .name = "C", .n_atoms = 21,
    .atom_name = (char**)C_atom_name,
    .atom_radius = (double*)C_atom_radius,
    .atom_class = (int*)C_atom_class };

static const char *DT_atom_name[] = {"N3", "OP1", "C3'", "C2", "C6", "N1", "C5", "C1'", "O2", "P", "C7", "O4'", "O3'", "C4", "C5'", "OP2", "C2'", "C4'", "O5'", "OP3", "O4", };
static double DT_atom_radius[] = {1.64, 1.42, 1.88, 1.61, 1.76, 1.64, 1.61, 1.88, 1.42, 1.8, 1.88, 1.46, 1.46, 1.61, 1.88, 1.46, 1.88, 1.88, 1.46, 1.46, 1.42, };
static int DT_atom_class[] = {1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, };
static struct classifier_residue DT_cfg = {
    .name = "DT", .n_atoms = 21,
    .atom_name = (char**)DT_atom_name,
    .atom_radius = (double*)DT_atom_radius,
    .atom_class = (int*)DT_atom_class };

static const char *A_atom_name[] = {"N9", "N3", "OP1", "C3'", "C8", "C2", "N1", "C6", "N6", "C5", "C1'", "P", "N7", "O4'", "O3'", "C4", "C5'", "OP2", "C2'", "C4'", "O5'", "OP3", "O2'", };
static double A_atom_radius[] = {1.64, 1.64, 1.42, 1.88, 1.76, 1.76, 1.64, 1.61, 1.64, 1.61, 1.88, 1.8, 1.64, 1.46, 1.46, 1.61, 1.88, 1.46, 1.88, 1.88, 1.46, 1.46, 1.46, };
static int A_atom_class[] = {1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, };
static struct classifier_residue A_cfg = {
    .name = "A", .n_atoms = 23,
    .atom_name = (char**)A_atom_name,
    .atom_radius = (double*)A_atom_radius,
    .atom_class = (int*)A_atom_class };

static const char *LEU_atom_name[] = {"O", "N", "CB", "CD1", "CD2", "C", "CG", "CA", "OXT", };
static double LEU_atom_radius[] = {1.42, 1.64, 1.88, 1.88, 1.88, 1.61, 1.88, 1.88, 1.46, };
static int LEU_atom_class[] = {1, 1, 0, 0, 0, 0, 0, 0, 1, };
static struct classifier_residue LEU_cfg = {
    .name = "LEU", .n_atoms = 9,
    .atom_name = (char**)LEU_atom_name,
    .atom_radius = (double*)LEU_atom_radius,
    .atom_class = (int*)LEU_atom_class };

static const char *ARG_atom_name[] = {"O", "N", "CB", "CD", "CZ", "C", "CG", "NE", "NH2", "NH1", "CA", "OXT", };
static double ARG_atom_radius[] = {1.42, 1.64, 1.88, 1.88, 1.61, 1.61, 1.88, 1.64, 1.64, 1.64, 1.88, 1.46, };
static int ARG_atom_class[] = {1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, };
static struct classifier_residue ARG_cfg = {
    .name = "ARG", .n_atoms = 12,
    .atom_name = (char**)ARG_atom_name,
    .atom_radius = (double*)ARG_atom_radius,
    .atom_class = (int*)ARG_atom_class };

static const char *THR_atom_name[] = {"O", "N", "CB", "CG2", "OG1", "C", "CA", "OXT", };
static double THR_atom_radius[] = {1.42, 1.64, 1.88, 1.88, 1.46, 1.61, 1.88, 1.46, };
static int THR_atom_class[] = {1, 1, 0, 0, 1, 0, 0, 1, };
static struct classifier_residue THR_cfg = {
    .name = "THR", .n_atoms = 8,
    .atom_name = (char**)THR_atom_name,
    .atom_radius = (double*)THR_atom_radius,
    .atom_class = (int*)THR_atom_class };

static const char *DA_atom_name[] = {"N9", "N3", "OP1", "C3'", "C8", "C2", "N1", "C6", "N6", "C5", "C1'", "P", "N7", "O4'", "O3'", "C4", "C5'", "OP2", "C2'", "C4'", "O5'", "OP3", };
static double DA_atom_radius[] = {1.64, 1.64, 1.42, 1.88, 1.76, 1.76, 1.64, 1.61, 1.64, 1.61, 1.88, 1.8, 1.64, 1.46, 1.46, 1.61, 1.88, 1.46, 1.88, 1.88, 1.46, 1.46, };
static int DA_atom_class[] = {1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, };
static struct classifier_residue DA_cfg = {
    .name = "DA", .n_atoms = 22,
    .atom_name = (char**)DA_atom_name,
    .atom_radius = (double*)DA_atom_radius,
    .atom_class = (int*)DA_atom_class };

static struct classifier_residue *residue_cfg[] = {
    &ACE_cfg, &T_cfg, &PRO_cfg, &ILE_cfg, &ASX_cfg, &CYS_cfg, &GLY_cfg, &DC_cfg, &NH2_cfg, &GLN_cfg, &SER_cfg, &DI_cfg, &ASN_cfg, &VAL_cfg, &TYR_cfg, &GLU_cfg, &ALA_cfg, &MET_cfg, &I_cfg, &HIS_cfg, &G_cfg, &PYL_cfg, &GLX_cfg, &DU_cfg, &U_cfg, &ASP_cfg, &SEC_cfg, &LYS_cfg, &HOH_cfg, &TRP_cfg, &DG_cfg, &PHE_cfg, &C_cfg, &DT_cfg, &A_cfg, &LEU_cfg, &ARG_cfg, &THR_cfg, &DA_cfg, };
static struct classifier_config freesasa_auto_config = {
    .n_residues = 39, .n_classes = 3,
    .residue_name = (char**)residue_name,
    .class_name = (char**)class_name,
    .residue = (struct classifier_residue **)residue_cfg
};

static void dummy_free(void *arg) {}

const freesasa_classifier freesasa_default_classifier = {
    .config = &freesasa_auto_config,
    .n_classes = 3,
    .radius = freesasa_classifier_config_radius,
    .sasa_class =freesasa_classifier_config_class,
    .class2str = freesasa_classifier_config_class2str,
    // Since this object is const, calling free should emit compiler warnings.
    .free_config = dummy_free, 
};
