/* config.h — generated by CMake (cmake/config.h.cmake).
   Mirrors the fields produced by autotools ./configure.
   Do not edit by hand; do not commit to version control. */

#ifndef FREESASA_CONFIG_H
#define FREESASA_CONFIG_H

#define PACKAGE_VERSION "@PROJECT_VERSION@"
#define PACKAGE_STRING  "FreeSASA @PROJECT_VERSION@"
#define PACKAGE_NAME    "freesasa"

/* Standard headers available */
#define HAVE_CONFIG_H   1
#define STDC_HEADERS    1

/* Feature flags — set at configure time.
   These may be overridden per-target with -D on the command line. */
#ifndef USE_THREADS
#define USE_THREADS 0
#endif

#ifndef USE_JSON
#define USE_JSON @USE_JSON@
#endif

#ifndef USE_XML
#define USE_XML @USE_XML@
#endif

/* USE_CHECK is always set per-target via -D; never override it here. */
#ifndef USE_CHECK
#define USE_CHECK 0
#endif

#ifndef INCLUDE_MEMERR_TESTS
#define INCLUDE_MEMERR_TESTS 0
#endif

/* Data paths filled in by CMake */
#ifndef DATADIR
#define DATADIR  "@TEST_DATADIR@"
#endif

#ifndef SHAREDIR
#define SHAREDIR "@TEST_SHAREDIR@"
#endif

/* URL strings */
#define REPORTBUG "Report bugs to <https://github.com/mittinatten/freesasa/issues>"
#define HOMEPAGE  "<http://freesasa.github.io>"
#define FREESASA_XMLNS "http://freesasa.github.io/"

/* Compiler attributes */
#ifndef __GNUC__
#define __attribute__(x)
#endif

#endif /* FREESASA_CONFIG_H */
